// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"
#include "ui_helpers.h"
#include <stdarg.h>
#include <stdio.h>
#include "../utils.h"
#include "../wifi_udp/mqtt.h"
#include "esp_log.h"

///////////////////// VARIABLES ////////////////////

// EVENTS
lv_obj_t * ui____initial_actions0;

// 活跃弹窗追踪：新弹窗触发时先销毁旧的，防止叠加
static lv_obj_t *g_active_overlay = NULL;

// IMAGES AND IMAGE SETS

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=0
    #error "LV_COLOR_16_SWAP should be 0 to match SquareLine Studio's settings"
#endif

///////////////////// FUNCTIONS ////////////////////

static void screen2_refresh_timer_cb(lv_timer_t *timer)
{
    lv_obj_t *act = lv_scr_act();
    if (act != NULL && act == ui_Screen2) {
        ui_refresh_screen2_labels();
    }
}

static void screen4_refresh_timer_cb(lv_timer_t *timer)
{
    lv_obj_t *act = lv_scr_act();
    if (act != NULL && act == ui_Screen4) {
        ui_refresh_screen4_labels();
    }
}

static void mqtt_cmd_timer_cb(lv_timer_t *timer)
{
    if (mqtt_cmd_queue == NULL) return;

    mqtt_cmd_item_t cmd_item;
    while (xQueueReceive(mqtt_cmd_queue, &cmd_item, 0) == pdPASS) {
        ESP_LOGI("MQTT_CMD", "Processing: %s", cmd_item.cmd);
        Command_Analysis(cmd_item.cmd);
    }
}

static void mqtt_sensor_timer_cb(lv_timer_t *timer)
{
    if (Open_mqtt_upload) {
        mqtt_send_sensor_json();
    }
}

static void popup_close_cb(lv_event_t *e)
{
    lv_obj_t *overlay = (lv_obj_t *)lv_event_get_user_data(e);
    g_active_overlay = NULL;
    lv_obj_del(overlay);
}

void Popup(char color, const char *format, ...)
{
    char buf[256];
    va_list args;
    va_start(args, format);
    vsnprintf(buf, sizeof(buf), format, args);
    va_end(args);

    lv_color_t bg;
    switch (color) {
        case 'r': bg = lv_color_hex(0xD43C0C); break;
        case 'y': bg = lv_color_hex(0xEDE878); break;
        case 'g': bg = lv_color_hex(0xB9DDD0); break;
        default:  bg = lv_color_hex(0xBEE3F6); break;
    }

    lv_obj_t *scr = lv_scr_act();

    // 若已有活跃弹窗，先销毁再建新的（防叠加）
    if (g_active_overlay != NULL) {
        lv_obj_del(g_active_overlay);
        g_active_overlay = NULL;
    }

    lv_coord_t sw = lv_obj_get_width(scr);
    lv_coord_t sh = lv_obj_get_height(scr);

    lv_obj_t *overlay = lv_obj_create(scr);
    lv_obj_set_size(overlay, sw, sh);
    lv_obj_set_pos(overlay, 0, 0);
    lv_obj_set_style_bg_opa(overlay, LV_OPA_50, 0);
    lv_obj_set_style_bg_color(overlay, lv_color_black(), 0);
    lv_obj_set_style_border_width(overlay, 0, 0);
    lv_obj_set_style_pad_all(overlay, 0, 0);
    lv_obj_clear_flag(overlay, LV_OBJ_FLAG_SCROLLABLE);

    lv_obj_t *box = lv_obj_create(overlay);
    lv_obj_set_style_bg_color(box, bg, 0);
    lv_obj_set_style_border_width(box, 0, 0);
    lv_obj_set_style_radius(box, 20, 0);
    lv_obj_set_style_shadow_width(box, 30, 0);
    lv_obj_set_style_shadow_opa(box, LV_OPA_40, 0);
    lv_obj_set_style_pad_top(box, 50, 0);
    lv_obj_set_style_pad_bottom(box, 30, 0);
    lv_obj_set_style_pad_left(box, 30, 0);
    lv_obj_set_style_pad_right(box, 30, 0);
    lv_obj_clear_flag(box, LV_OBJ_FLAG_SCROLLABLE);

    lv_obj_t *btn = lv_btn_create(box);
    lv_obj_set_size(btn, 44, 44);
    lv_obj_align(btn, LV_ALIGN_TOP_RIGHT, 0, -5);
    lv_obj_set_style_radius(btn, LV_RADIUS_CIRCLE, 0);
    lv_obj_set_style_bg_color(btn, lv_color_hex(0xE53935), 0);
    lv_obj_set_style_shadow_width(btn, 8, 0);
    lv_obj_set_style_shadow_opa(btn, LV_OPA_30, 0);

    lv_obj_t *x_label = lv_label_create(btn);
    lv_label_set_text(x_label, LV_SYMBOL_CLOSE);
    lv_obj_set_style_text_color(x_label, lv_color_white(), 0);
    lv_obj_set_style_text_font(x_label, &lv_font_montserrat_24, 0);
    lv_obj_center(x_label);

    lv_obj_add_event_cb(btn, popup_close_cb, LV_EVENT_CLICKED, overlay);

    lv_obj_t *label = lv_label_create(box);
    lv_label_set_text(label, buf);
    lv_obj_set_style_text_color(label, lv_color_black(), 0);
    lv_obj_set_style_text_font(label, &lv_font_montserrat_28, 0);
    lv_label_set_long_mode(label, LV_LABEL_LONG_WRAP);
    lv_obj_set_width(label, (sw * 7) / 10);

    lv_obj_update_layout(label);
    lv_coord_t bw = lv_obj_get_width(label) + 60;
    lv_coord_t bh = lv_obj_get_height(label) + 90;
    if (bw > sw - 40) bw = sw - 40;
    if (bw < 200) bw = 200;
    if (bh > sh - 40) bh = sh - 40;
    lv_obj_set_size(box, bw, bh);
    lv_obj_center(box);
    lv_obj_set_width(label, bw - 60);

    // 记录活跃弹窗，供下次调用时自动关闭
    g_active_overlay = overlay;
}

///////////////////// SCREENS ////////////////////

void ui_init(void)
{
    lv_disp_t * dispp = lv_disp_get_default();
    lv_theme_t * theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED),
                                               false, LV_FONT_DEFAULT);
    lv_disp_set_theme(dispp, theme);
    ui_Screen1_screen_init();
    ui_Screen2_screen_init();
    ui_Screen3_screen_init();
    ui_Screen4_screen_init();
    ui_Screen5_screen_init();
    ui____initial_actions0 = lv_obj_create(NULL);
    lv_disp_load_scr(ui_Screen1);

    // 全局刷新定时器：只在对应页面活跃时才刷新标签和图表
    lv_timer_create(screen2_refresh_timer_cb, 200, NULL);
    lv_timer_create(screen4_refresh_timer_cb, 200, NULL);
    lv_timer_create(mqtt_cmd_timer_cb, 100, NULL);
    lv_timer_create(mqtt_sensor_timer_cb, 1000, NULL);
}

void ui_destroy(void)
{
    ui_Screen1_screen_destroy();
    ui_Screen2_screen_destroy();
    ui_Screen3_screen_destroy();
    ui_Screen4_screen_destroy();
    ui_Screen5_screen_destroy();
}