// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef _SQUARELINE_PROJECT_UI_H
#define _SQUARELINE_PROJECT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"


///////////////////// SCREENS ////////////////////

#include "ui_Screen1.h"
#include "ui_Screen2.h"
#include "ui_Screen3.h"
#include "ui_Screen4.h"
#include "ui_Screen5.h"

///////////////////// VARIABLES ////////////////////


// EVENTS

extern lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE(ui_img_accounticon_png_png);    // assets/AccountIcon.png.png
LV_IMG_DECLARE(ui_img_loginicon_png);    // assets/LoginIcon.png
LV_IMG_DECLARE(ui_img_home1_png);    // assets/home1.png
LV_IMG_DECLARE(ui_img_home2_png);    // assets/home2.png
LV_IMG_DECLARE(ui_img_home3_png);    // assets/home3.png
LV_IMG_DECLARE(ui_img_home4_png);    // assets/home4.png

// UI INIT
void ui_init(void);
void ui_destroy(void);

// 通用弹窗：Popup('r'/'y'/'g', "format", ...) — 红色X关闭、大字体、自适应尺寸
void Popup(char color, const char *format, ...);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif