// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef UI_SCREEN3_H
#define UI_SCREEN3_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Screen3
extern void ui_Screen3_screen_init(void);
extern void ui_Screen3_screen_destroy(void);
extern lv_obj_t * ui_Screen3;
extern lv_obj_t * ui_Image3;
extern lv_obj_t * ui_Keyboard2;
extern void ui_event_Keyboard2(lv_event_t * e);
extern void ui_event_AiInp(lv_event_t * e);
extern lv_obj_t * ui_AiInp;
extern void ui_event_BackBtnc1(lv_event_t * e);
extern lv_obj_t * ui_BackBtnc1;
extern lv_obj_t * ui_dqtd;
extern lv_obj_t * ui_zxd;
extern lv_obj_t * ui_haoshi;
extern lv_obj_t * ui_sctl;
extern void ui_event_kszdBtnc(lv_event_t * e);
extern lv_obj_t * ui_kszdBtnc;
extern void ui_event_ksbgBtnc(lv_event_t * e);
extern lv_obj_t * ui_ksbgBtnc;
extern void ui_event_jycsBtnc(lv_event_t * e);
extern lv_obj_t * ui_jycsBtnc;
extern void ui_event_xdhBtnc(lv_event_t * e);
extern lv_obj_t * ui_xdhBtnc;
extern void ui_event_bcdhBtnc(lv_event_t * e);
extern lv_obj_t * ui_bcdhBtnc;
extern void ui_event_fsBtnc(lv_event_t * e);
extern lv_obj_t * ui_fsBtnc;
extern lv_obj_t * ui_zhishiLabel;
extern void ui_event_toSetBtnc(lv_event_t * e);
extern lv_obj_t * ui_toSetBtnc;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif