// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"
#include "utils.h"
#include "esp_log.h"
#include "../wifi_udp/llm_cloud.h"

static const char *TAG2 = "Screen3_LOG";
static lv_timer_t *ui_llm_timer = NULL;
static lv_obj_t *current_ai_label = NULL;
static bool ai_busy = false;              // 防止快速点击导致并发请求

// AI 对话缓存（全局链表存储，页面跳转不丢失）
static char *g_pending_question = NULL;   // 待存储的用户问题（堆分配）

// 从utils.h中引入Screen3的全局变量
extern char Screen3_dqtd_text[32];
extern char Screen3_zxd_text[32];
extern char Screen3_haoshi_text[32];
extern char Screen3_sctl_text[32];
extern char Screen3_zhishiLabel_text[64];

// Chart2 数据直接读取静态数组（避免访问可能已释放的 LVGL 对象）
// ui_Chart2_series_1_array / ui_Chart2_series_2_array 声明于 utils.h

// 噪声度 & 抖动度历史数组
extern char sound_level_history[7][16];
extern char jitter_level_history[7][16];

lv_obj_t * ui_Screen3 = NULL;
lv_obj_t * ui_Image3 = NULL;
lv_obj_t * ui_Keyboard2 = NULL;
lv_obj_t * ui_AiInp = NULL;
lv_obj_t * ui_BackBtnc1 = NULL;
lv_obj_t * ui_dqtd = NULL;
lv_obj_t * ui_zxd = NULL;
lv_obj_t * ui_haoshi = NULL;
lv_obj_t * ui_sctl = NULL;
lv_obj_t * ui_kszdBtnc = NULL;
lv_obj_t * ui_ksbgBtnc = NULL;
lv_obj_t * ui_jycsBtnc = NULL;
lv_obj_t * ui_xdhBtnc = NULL;
lv_obj_t * ui_bcdhBtnc = NULL;
lv_obj_t * ui_fsBtnc = NULL;
lv_obj_t * ui_zhishiLabel = NULL;
lv_obj_t * ui_toSetBtnc = NULL;
// 聊天容器
lv_obj_t * ui_ChatContainer = NULL;

// 函数声明  -----------------
void add_chat_bubble(const char *text, bool is_user);

// 核心定时器逻辑：从队列读取流式 Token，累积到 LVGL 气泡标签中
// [DONE] 到达时，直接从气泡标签取完整回复文本，存入全局链表
static void llm_check_timer_cb(lv_timer_t * timer) {
    if (llm_reply_queue == NULL) return;

    char *ai_reply_text = NULL;
    
    while (xQueueReceive(llm_reply_queue, &ai_reply_text, 0) == pdPASS) {
        if (ai_reply_text != NULL) {
            
            if (strcmp(ai_reply_text, "[DONE]") == 0) {
                ESP_LOGI(TAG2, "UI: stream transfer fully completed");

                // 直接从 LVGL 气泡标签取完整回复文本（无需额外缓冲）
                const char *full_reply = "";
                if (current_ai_label != NULL) {
                    full_reply = lv_label_get_text(current_ai_label);
                }
                
                if (g_pending_question != NULL && full_reply != NULL && full_reply[0] != '\0') {
                    ESP_LOGI(TAG2, "Save Q&A pair to global list: Q='%s' A='%s'", g_pending_question, full_reply);
                    ai_msg_add(g_pending_question, full_reply);
                } else {
                    ESP_LOGW(TAG2, "Skip save: pending=%p reply=%s", g_pending_question, full_reply);
                }
                
                // 清理临时缓冲
                if (g_pending_question != NULL) {
                    free(g_pending_question);
                    g_pending_question = NULL;
                }
                current_ai_label = NULL;
                
                free(ai_reply_text);
                
                if (ui_llm_timer != NULL) {
                    lv_timer_pause(ui_llm_timer);
                    ESP_LOGI(TAG2, "Timer paused, release CPU");
                }
                ai_busy = false;
                continue; 
            }

            if (current_ai_label == NULL) {
                ESP_LOGI(TAG2, "First streaming token, create new AI bubble: %s", ai_reply_text);
                add_chat_bubble(ai_reply_text, false); 
            } else {
                lv_label_ins_text(current_ai_label, LV_LABEL_POS_LAST, ai_reply_text);
                
                lv_obj_t *bubble = lv_obj_get_parent(current_ai_label);
                lv_obj_scroll_to_view_recursive(bubble, LV_ANIM_OFF);
            }

            free(ai_reply_text); 
        }
    }
}

// 添加聊天气泡
void add_chat_bubble(const char *text, bool is_user) {
    // 创建气泡容器
    lv_obj_t *bubble = lv_obj_create(ui_ChatContainer);
    lv_obj_set_width(bubble, 250); 
    lv_obj_set_height(bubble, LV_SIZE_CONTENT); 
    
    if(is_user) {
        lv_obj_set_align(bubble, LV_ALIGN_TOP_RIGHT); 
        lv_obj_set_style_bg_color(bubble, lv_palette_main(LV_PALETTE_BLUE), 0);
    } else {
        lv_obj_set_align(bubble, LV_ALIGN_TOP_LEFT);
        lv_obj_set_style_bg_color(bubble, lv_palette_main(LV_PALETTE_GREY), 0);
    }

    lv_obj_set_style_radius(bubble, 10, 0);
    lv_obj_set_style_border_width(bubble, 0, 0);
    lv_obj_set_style_pad_all(bubble, 8, 0); 

    // 创建文字 Label
    lv_obj_t *label = lv_label_create(bubble);
    lv_label_set_long_mode(label, LV_LABEL_LONG_WRAP); 
    lv_label_set_text(label, text);
    lv_obj_set_width(label, lv_pct(100)); 
    lv_obj_set_style_text_color(label, lv_color_white(), 0);
    lv_obj_set_style_text_align(label, LV_TEXT_ALIGN_LEFT, 0); 
    
    // 如果是 AI 产生的气泡，绑定到全局静态变量，供定时器后续追加
    if (!is_user) {
        current_ai_label = label;
    }

    // 自动滚动到最新消息
    lv_obj_scroll_to_view_recursive(bubble, LV_ANIM_ON);
}

// event funtions
// 输入框事件
void ui_event_AiInp(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_FOCUSED) {
        // 显示键盘
        _ui_flag_modify(ui_Keyboard2, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
        
        // 将键盘移到所有子对象的最后面（即最顶层）
        lv_obj_move_foreground(ui_Keyboard2);
    }
    
    if(event_code == LV_EVENT_CLICKED) {
        _ui_keyboard_set_target(ui_Keyboard2, ui_AiInp);
    }
    
    if(event_code == LV_EVENT_DEFOCUSED) {
        // 隐藏键盘
        _ui_flag_modify(ui_Keyboard2, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
    }
}

void ui_event_Keyboard2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        lv_btnmatrix_clear_btn_ctrl_all(ui_Keyboard2, LV_BTNMATRIX_CTRL_POPOVER);
    }
}

// 返回主界面按钮
void ui_event_BackBtnc1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Screen2, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_Screen2_screen_init);
    }
}

// ── 复用：构建诊断数据（电压/电流/抖动/噪声/诊断/置信度） ──
static int build_diagnosis_data(char *buf, int buf_size)
{
    int off = 0;
    bool first;
    uint16_t i;
    uint16_t pt_count = CHART2_DATA_POINTS;

    off += snprintf(buf + off, buf_size - off, "voltage=[");
    first = true;
    for (i = 0; i < pt_count && off < buf_size - 8; i++) {
        off += snprintf(buf + off, buf_size - off,
                        "%s%.2f", first ? "" : ",", ui_Chart2_series_2_array[i] / 100.0);
        first = false;
    }
    off += snprintf(buf + off, buf_size - off, "]");

    off += snprintf(buf + off, buf_size - off, ", current=[");
    first = true;
    for (i = 0; i < pt_count && off < buf_size - 8; i++) {
        off += snprintf(buf + off, buf_size - off,
                        "%s%.2f", first ? "" : ",", ui_Chart2_series_1_array[i] / 100.0);
        first = false;
    }
    off += snprintf(buf + off, buf_size - off, "]");

    off += snprintf(buf + off, buf_size - off, ", jitter=[");
    first = true;
    for (i = 0; i < HISTORY_WINDOW; i++) {
        if (jitter_level_history[i][0] != '\0') {
            off += snprintf(buf + off, buf_size - off,
                            "%s%s", first ? "" : ",", jitter_level_history[i]);
            first = false;
        }
    }
    off += snprintf(buf + off, buf_size - off, "]");

    off += snprintf(buf + off, buf_size - off, ", noise=[");
    first = true;
    for (i = 0; i < HISTORY_WINDOW; i++) {
        if (sound_level_history[i][0] != '\0') {
            off += snprintf(buf + off, buf_size - off,
                            "%s%s", first ? "" : ",", sound_level_history[i]);
            first = false;
        }
    }
    off += snprintf(buf + off, buf_size - off, "]");

    off += snprintf(buf + off, buf_size - off,
                    ", diagnosis=%s, confidence=%s",
                    Screen3_dqtd_text, Screen3_zxd_text);
    return off;
}

// ── 复用：展示气泡 + 发送 AI 请求 ──
static void send_ai_prompt(const char *prompt, const char *display_text)
{
    if (ai_busy) {
        ESP_LOGW(TAG2, "AI request in progress, ignoring rapid click");
        return;
    }
    ai_busy = true;

    add_chat_bubble(display_text, true);

    current_ai_label = NULL;
    if (g_pending_question != NULL) free(g_pending_question);
    g_pending_question = (char *)malloc(strlen(display_text) + 1);
    if (g_pending_question != NULL) {
        strcpy(g_pending_question, display_text);
    }

    lv_refr_now(NULL);

    if (ui_llm_timer != NULL) {
        lv_timer_resume(ui_llm_timer);
    }

    esp_err_t err = llm_cloud_request_stream(prompt);
    if (err != ESP_OK) {
        add_chat_bubble("request error: please try again later", false);
        if (ui_llm_timer != NULL) {
            lv_timer_pause(ui_llm_timer);
        }
        current_ai_label = NULL;  // 失败时复位，避免下次追加到错误气泡
        ai_busy = false;
    }
}

// 开始诊断按钮
void ui_event_kszdBtnc(lv_event_t * e)
{
    if (lv_event_get_code(e) == LV_EVENT_CLICKED) {
        char prompt[2048];
        int off = snprintf(prompt, sizeof(prompt), "Based on ");
        off += build_diagnosis_data(prompt + off, sizeof(prompt) - off);
        snprintf(prompt + off, sizeof(prompt) - off,
                 " verify the MCU diagnosis accuracy and share your analysis.");
        send_ai_prompt(prompt, "Please conduct an analysis");
    }
}

// 快速报告按钮
void ui_event_ksbgBtnc(lv_event_t * e)
{
    if (lv_event_get_code(e) == LV_EVENT_CLICKED) {
        char prompt[2048];
        int off = snprintf(prompt, sizeof(prompt),
                "Click the Quick Report button to generate itemized quality analysis for ");
        off += build_diagnosis_data(prompt + off, sizeof(prompt) - off);
        snprintf(prompt + off, sizeof(prompt) - off,
                 " analyze each indicator separately and locate the root of all anomalies.");
        send_ai_prompt(prompt, "Generate itemized quality analysis");
    }
}

// 建议措施按钮
void ui_event_jycsBtnc(lv_event_t * e)
{
    if (lv_event_get_code(e) == LV_EVENT_CLICKED) {
        char prompt[2048];
        int off = snprintf(prompt, sizeof(prompt), "Please analyze ");
        off += build_diagnosis_data(prompt + off, sizeof(prompt) - off);
        snprintf(prompt + off, sizeof(prompt) - off,
                 " and provide targeted improvement measures for all detected abnormalities.");
        send_ai_prompt(prompt, "Provide targeted improvement measures");
    }
}

// 新对话按钮
void ui_event_xdhBtnc(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        ai_busy = false;
        current_ai_label = NULL;  // 防止悬空指针：清空容器后旧的 AI 气泡已失效
        // 清空全局链表（数据层）
        ai_msg_clear();
        // 清空聊天容器（UI层）
        if(ui_ChatContainer != NULL) {
            lv_obj_clean(ui_ChatContainer);
        }

    }
}

// 保存对话按钮
void ui_event_bcdhBtnc(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Screen1, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_Screen1_screen_init);
    }
}

// 发送按钮
void ui_event_fsBtnc(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        if (ai_busy) {
            ESP_LOGW(TAG2, "AI request in progress, ignoring rapid send");
            return;
        }
        const char *txt = lv_textarea_get_text(ui_AiInp);
        
        if(strlen(txt) > 0) {
            ai_busy = true;
            ESP_LOGI(TAG2, "Add user bubble: %s", txt);
            add_chat_bubble(txt, true);

            // 每次发送新问题时，强制复位 AI 气泡指针，确保新回复创建新气泡
            current_ai_label = NULL;

            // 保存当前问题到临时缓冲（等待 AI 回复完成后一并存入全局链表）
            if (g_pending_question != NULL) free(g_pending_question);
            g_pending_question = (char *)malloc(strlen(txt) + 1);
            if (g_pending_question != NULL) {
                strcpy(g_pending_question, txt);
            } else {
                ESP_LOGE(TAG2, "Failed to alloc pending question!");
            }
            
            lv_refr_now(NULL); 
            ESP_LOGI(TAG2, "screen refresh done");

            // 启动定时器，准备接收流式响应
            if (ui_llm_timer != NULL) {
                lv_timer_resume(ui_llm_timer);
                ESP_LOGI(TAG2, "Timer started, ready to receive AI response");
            }

            // 调用你的网络
            esp_err_t err = llm_cloud_request_stream(txt);
            
            ESP_LOGI(TAG2, "network layer done");
            if(err != ESP_OK) {
                add_chat_bubble("request error: please try again later", false);
                if (ui_llm_timer != NULL) {
                    lv_timer_pause(ui_llm_timer);
                }
                ai_busy = false;
            } else {
                lv_textarea_set_text(ui_AiInp, "");
            }
        }
    }
}

// 前往设置按钮
void ui_event_toSetBtnc(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Screen5, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_Screen5_screen_init);
    }
}

// Screen3 被删除时的回调：暂停定时器 + 复位悬空指针
static void screen3_delete_cb(lv_event_t * e)
{
    ESP_LOGI(TAG2, "Screen3 closing, cleanup timer and pointers");
    if (ui_llm_timer != NULL) {
        lv_timer_pause(ui_llm_timer);
    }
    current_ai_label = NULL;
    // 中途退出时若有未保存的问答，尝试保存
    if (g_pending_question != NULL) {
        ESP_LOGW(TAG2, "Screen3 exit with unfinished Q&A: '%s'", g_pending_question);
        free(g_pending_question);
        g_pending_question = NULL;
    }
}

// build funtions
void ui_Screen3_screen_init(void)
{
    ui_Screen3 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_add_event_cb(ui_Screen3, screen3_delete_cb, LV_EVENT_DELETE, NULL);

    ui_Image3 = lv_img_create(ui_Screen3);
    lv_img_set_src(ui_Image3, &ui_img_home2_png);
    lv_obj_set_width(ui_Image3, 800);
    lv_obj_set_height(ui_Image3, 480);
    lv_obj_set_align(ui_Image3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image3, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_Image3, 259);

    ui_Keyboard2 = lv_keyboard_create(ui_Screen3);
    lv_obj_set_width(ui_Keyboard2, 800);
    lv_obj_set_height(ui_Keyboard2, 302);
    lv_obj_set_x(ui_Keyboard2, -2);
    lv_obj_set_y(ui_Keyboard2, -94);
    lv_obj_set_align(ui_Keyboard2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Keyboard2, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_keyboard_set_popovers(ui_Keyboard2, false);
    lv_btnmatrix_clear_btn_ctrl_all(ui_Keyboard2, LV_BTNMATRIX_CTRL_POPOVER);

    ui_AiInp = lv_textarea_create(ui_Screen3);
    lv_obj_set_width(ui_AiInp, 348);
    lv_obj_set_height(ui_AiInp, 74);
    lv_obj_set_x(ui_AiInp, -206);
    lv_obj_set_y(ui_AiInp, 177);
    lv_obj_set_align(ui_AiInp, LV_ALIGN_CENTER);
    lv_textarea_set_placeholder_text(ui_AiInp, "Ask Me Anything!");
    lv_obj_add_flag(ui_AiInp, LV_OBJ_FLAG_FLOATING);     /// Flags
    lv_obj_set_style_text_color(ui_AiInp, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_AiInp, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_AiInp, lv_color_hex(0x102831), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_AiInp, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_AiInp, lv_color_hex(0x31517A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_AiInp, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BackBtnc1 = lv_obj_create(ui_Screen3);
    lv_obj_remove_style_all(ui_BackBtnc1);
    lv_obj_set_width(ui_BackBtnc1, 63);
    lv_obj_set_height(ui_BackBtnc1, 55);
    lv_obj_set_x(ui_BackBtnc1, -358);
    lv_obj_set_y(ui_BackBtnc1, -199);
    lv_obj_set_align(ui_BackBtnc1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_BackBtnc1, LV_OBJ_FLAG_CLICKABLE);
    lv_obj_clear_flag(ui_BackBtnc1, LV_OBJ_FLAG_SCROLLABLE);

    ui_dqtd = lv_label_create(ui_Screen3);
    lv_obj_set_width(ui_dqtd, 210);
    lv_obj_set_height(ui_dqtd, 21);
    lv_obj_set_x(ui_dqtd, 256);
    lv_obj_set_y(ui_dqtd, -108);
    lv_obj_set_align(ui_dqtd, LV_ALIGN_CENTER);
    lv_label_set_text(ui_dqtd, Screen3_dqtd_text);
    lv_obj_set_style_text_color(ui_dqtd, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_dqtd, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_dqtd, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_dqtd, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_zxd = lv_label_create(ui_Screen3);
    lv_obj_set_width(ui_zxd, 210);
    lv_obj_set_height(ui_zxd, 21);
    lv_obj_set_x(ui_zxd, 256);
    lv_obj_set_y(ui_zxd, -83);
    lv_obj_set_align(ui_zxd, LV_ALIGN_CENTER);
    lv_label_set_text(ui_zxd, Screen3_zxd_text);
    lv_obj_set_style_text_color(ui_zxd, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_zxd, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_zxd, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_zxd, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_haoshi = lv_label_create(ui_Screen3);
    lv_obj_set_width(ui_haoshi, 210);
    lv_obj_set_height(ui_haoshi, 21);
    lv_obj_set_x(ui_haoshi, 256);
    lv_obj_set_y(ui_haoshi, -59);
    lv_obj_set_align(ui_haoshi, LV_ALIGN_CENTER);
    lv_label_set_text(ui_haoshi, Screen3_haoshi_text);
    lv_obj_set_style_text_color(ui_haoshi, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_haoshi, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_haoshi, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_haoshi, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_sctl = lv_label_create(ui_Screen3);
    lv_obj_set_width(ui_sctl, 210);
    lv_obj_set_height(ui_sctl, 21);
    lv_obj_set_x(ui_sctl, 256);
    lv_obj_set_y(ui_sctl, -36);
    lv_obj_set_align(ui_sctl, LV_ALIGN_CENTER);
    lv_label_set_text(ui_sctl, Screen3_sctl_text);
    lv_obj_set_style_text_color(ui_sctl, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_sctl, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_sctl, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_sctl, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_kszdBtnc = lv_obj_create(ui_Screen3);
    lv_obj_remove_style_all(ui_kszdBtnc);
    lv_obj_set_width(ui_kszdBtnc, 125);
    lv_obj_set_height(ui_kszdBtnc, 34);
    lv_obj_set_x(ui_kszdBtnc, 309);
    lv_obj_set_y(ui_kszdBtnc, 112);
    lv_obj_set_align(ui_kszdBtnc, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_kszdBtnc, LV_OBJ_FLAG_CLICKABLE);
    lv_obj_clear_flag(ui_kszdBtnc, LV_OBJ_FLAG_SCROLLABLE);

    ui_ksbgBtnc = lv_obj_create(ui_Screen3);
    lv_obj_remove_style_all(ui_ksbgBtnc);
    lv_obj_set_width(ui_ksbgBtnc, 125);
    lv_obj_set_height(ui_ksbgBtnc, 34);
    lv_obj_set_x(ui_ksbgBtnc, 309);
    lv_obj_set_y(ui_ksbgBtnc, 153);
    lv_obj_set_align(ui_ksbgBtnc, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ksbgBtnc, LV_OBJ_FLAG_CLICKABLE);
    lv_obj_clear_flag(ui_ksbgBtnc, LV_OBJ_FLAG_SCROLLABLE);

    ui_jycsBtnc = lv_obj_create(ui_Screen3);
    lv_obj_remove_style_all(ui_jycsBtnc);
    lv_obj_set_width(ui_jycsBtnc, 125);
    lv_obj_set_height(ui_jycsBtnc, 34);
    lv_obj_set_x(ui_jycsBtnc, 308);
    lv_obj_set_y(ui_jycsBtnc, 195);
    lv_obj_set_align(ui_jycsBtnc, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_jycsBtnc, LV_OBJ_FLAG_CLICKABLE);
    lv_obj_clear_flag(ui_jycsBtnc, LV_OBJ_FLAG_SCROLLABLE);

    ui_xdhBtnc = lv_obj_create(ui_Screen3);
    lv_obj_remove_style_all(ui_xdhBtnc);
    lv_obj_set_width(ui_xdhBtnc, 90);
    lv_obj_set_height(ui_xdhBtnc, 28);
    lv_obj_set_x(ui_xdhBtnc, -330);
    lv_obj_set_y(ui_xdhBtnc, 120);
    lv_obj_set_align(ui_xdhBtnc, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_xdhBtnc, LV_OBJ_FLAG_CLICKABLE);
    lv_obj_clear_flag(ui_xdhBtnc, LV_OBJ_FLAG_SCROLLABLE);

    ui_bcdhBtnc = lv_obj_create(ui_Screen3);
    lv_obj_remove_style_all(ui_bcdhBtnc);
    lv_obj_set_width(ui_bcdhBtnc, 104);
    lv_obj_set_height(ui_bcdhBtnc, 28);
    lv_obj_set_x(ui_bcdhBtnc, -223);
    lv_obj_set_y(ui_bcdhBtnc, 119);
    lv_obj_set_align(ui_bcdhBtnc, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_bcdhBtnc, LV_OBJ_FLAG_CLICKABLE);
    lv_obj_clear_flag(ui_bcdhBtnc, LV_OBJ_FLAG_SCROLLABLE);

    ui_fsBtnc = lv_obj_create(ui_Screen3);
    lv_obj_remove_style_all(ui_fsBtnc);
    lv_obj_set_width(ui_fsBtnc, 42);
    lv_obj_set_height(ui_fsBtnc, 47);
    lv_obj_set_x(ui_fsBtnc, -6);
    lv_obj_set_y(ui_fsBtnc, 191);
    lv_obj_set_align(ui_fsBtnc, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_fsBtnc, LV_OBJ_FLAG_CLICKABLE);
    lv_obj_clear_flag(ui_fsBtnc, LV_OBJ_FLAG_SCROLLABLE);

    ui_zhishiLabel = lv_label_create(ui_Screen3);
    lv_obj_set_width(ui_zhishiLabel, 204);
    lv_obj_set_height(ui_zhishiLabel, 38);
    lv_obj_set_x(ui_zhishiLabel, 279);
    lv_obj_set_y(ui_zhishiLabel, -203);
    lv_obj_set_align(ui_zhishiLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_zhishiLabel, Screen3_zhishiLabel_text);
    lv_obj_set_style_text_color(ui_zhishiLabel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_zhishiLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_zhishiLabel, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_zhishiLabel, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_toSetBtnc = lv_obj_create(ui_Screen3);
    lv_obj_remove_style_all(ui_toSetBtnc);
    lv_obj_set_width(ui_toSetBtnc, 166);
    lv_obj_set_height(ui_toSetBtnc, 59);
    lv_obj_set_x(ui_toSetBtnc, 24);
    lv_obj_set_y(ui_toSetBtnc, -202);
    lv_obj_set_align(ui_toSetBtnc, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_toSetBtnc, LV_OBJ_FLAG_CLICKABLE);
    lv_obj_clear_flag(ui_toSetBtnc, LV_OBJ_FLAG_SCROLLABLE);

    
    // 聊天容器
    ui_ChatContainer = lv_obj_create(ui_Screen3);
    lv_obj_set_pos(ui_ChatContainer, 31, 101); // 设置坐标
    lv_obj_set_size(ui_ChatContainer, 370, 227); // 401-31, 328-101
    lv_obj_set_flex_flow(ui_ChatContainer, LV_FLEX_FLOW_COLUMN); // 垂直布局
    lv_obj_set_flex_align(ui_ChatContainer, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_add_flag(ui_ChatContainer, LV_OBJ_FLAG_SCROLLABLE);
    lv_obj_set_style_bg_opa(ui_ChatContainer, 0, 0);       // 背景透明度为0
    lv_obj_set_style_border_width(ui_ChatContainer, 0, 0); // 无边框
    lv_obj_set_style_pad_all(ui_ChatContainer, 5, 0);      // 适当内边距

    // 创建一个定时器，用于检查队列是否有数据
    if (ui_llm_timer == NULL) {
        ui_llm_timer = lv_timer_create(llm_check_timer_cb, 100, NULL);
        lv_timer_pause(ui_llm_timer); // 初始暂停，发送消息时再启动
        ESP_LOGI(TAG2, "成功创建大模型检测定时器（初始暂停状态）");
    }

    // 从全局链表恢复历史对话气泡（页面跳转后不丢失）
    {
        ai_msg_node_t *cur = ai_msg_get_head();
        uint8_t restored = 0;
        while (cur != NULL) {
            if (cur->question != NULL) {
                add_chat_bubble(cur->question, true);
            }
            if (cur->answer != NULL) {
                add_chat_bubble(cur->answer, false);
            }
            cur = cur->next;
            restored++;
        }
        ESP_LOGI(TAG2, "Restored %d Q&A pairs from global list", restored);
        current_ai_label = NULL;  // 重建后复位，避免新回复追加到旧气泡
    }

    lv_obj_add_event_cb(ui_AiInp, ui_event_AiInp, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_BackBtnc1, ui_event_BackBtnc1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_kszdBtnc, ui_event_kszdBtnc, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ksbgBtnc, ui_event_ksbgBtnc, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_jycsBtnc, ui_event_jycsBtnc, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_xdhBtnc, ui_event_xdhBtnc, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_bcdhBtnc, ui_event_bcdhBtnc, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_fsBtnc, ui_event_fsBtnc, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_toSetBtnc, ui_event_toSetBtnc, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Keyboard2, ui_event_Keyboard2, LV_EVENT_ALL, NULL);

}

void ui_Screen3_screen_destroy(void)
{   
    if(ui_llm_timer != NULL) {
        lv_timer_del(ui_llm_timer);
        ui_llm_timer = NULL;
        ESP_LOGI(TAG2, "Safe unregister llm timer");
    }
    if(ui_Screen3) lv_obj_del(ui_Screen3);
    // NULL screen variables
    ui_Screen3 = NULL;
    ui_Image3 = NULL;
    ui_Keyboard2 = NULL;
    ui_AiInp = NULL;
    ui_BackBtnc1 = NULL;
    ui_dqtd = NULL;
    ui_zxd = NULL;
    ui_haoshi = NULL;
    ui_sctl = NULL;
    ui_kszdBtnc = NULL;
    ui_ksbgBtnc = NULL;
    ui_jycsBtnc = NULL;
    ui_xdhBtnc = NULL;
    ui_bcdhBtnc = NULL;
    ui_fsBtnc = NULL;
    ui_zhishiLabel = NULL;
    ui_toSetBtnc = NULL;

}