// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef UI_SCREEN4_H
#define UI_SCREEN4_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Screen4
extern void ui_Screen4_screen_init(void);
extern void ui_Screen4_screen_destroy(void);
extern lv_obj_t * ui_Screen4;
extern lv_obj_t * ui_Image4;
extern void ui_event_BackHome1Btnc(lv_event_t * e);
extern lv_obj_t * ui_BackHome1Btnc;
extern lv_obj_t * ui_PositionModeSelecter;
extern lv_obj_t * ui_SpeedModeSelecter;
extern void ui_event_PositionModeSelecter(lv_event_t * e);
extern void ui_event_SpeedModeSelecter(lv_event_t * e);
extern lv_obj_t * ui_RoundtripMode;
extern void ui_event_RoundtripMode(lv_event_t * e);
extern lv_obj_t * ui_ConsoleMode;
extern void ui_event_ConsoleMode(lv_event_t * e);
extern lv_obj_t * ui_TargetLocation;
extern void ui_event_TargetLocation(lv_event_t * e);
extern void ui_event_LowerLimitPosition(lv_event_t * e);
extern lv_obj_t * ui_LowerLimitPosition;
extern void ui_event_HighLimitPosition(lv_event_t * e);
extern lv_obj_t * ui_HighLimitPosition;
extern void ui_event_CurrentSpeed(lv_event_t * e);
extern lv_obj_t * ui_CurrentSpeed;
extern void ui_event_CurrentAcc(lv_event_t * e);
extern lv_obj_t * ui_CurrentAcc;
extern lv_obj_t * ui_KeyboardSc4up;
extern void ui_event_KeyboardSc4up(lv_event_t * e);
extern void ui_event_GoLeftBtnc(lv_event_t * e);
extern lv_obj_t * ui_GoLeftBtnc;
extern void ui_event_GoRightBtnc(lv_event_t * e);
extern lv_obj_t * ui_GoRightBtnc;
extern void ui_event_GoOnBtnc(lv_event_t * e);
extern lv_obj_t * ui_GoOnBtnc;
extern void ui_event_GoStopBtnc(lv_event_t * e);
extern lv_obj_t * ui_GoStopBtnc;
extern void ui_event_Back0Btnc(lv_event_t * e);
extern lv_obj_t * ui_Back0Btnc;
extern void ui_event_toSetBtnc2(lv_event_t * e);
extern lv_obj_t * ui_toSetBtnc2;
extern lv_obj_t * ui_Label5;
extern lv_obj_t * ui_KeyboardSc4down;
extern void ui_event_KeyboardSc4down(lv_event_t * e);
extern lv_obj_t * ui_LabelDeviceOnline;
extern lv_obj_t * ui_LabelSpeed;
extern lv_obj_t * ui_LabelPosition;
extern lv_obj_t * ui_LabelPhaseCurrent;

// CUSTOM VARIABLES
typedef enum {
    SCREEN4_MODE_CONSOLE = 0,
    SCREEN4_MODE_POSITION,
    SCREEN4_MODE_SPEED
} screen4_op_mode_t;

extern screen4_op_mode_t g_screen4_current_mode;
extern bool g_screen4_roundtrip_enabled;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif