// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef UI_SCREEN2_H
#define UI_SCREEN2_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Screen2
extern void ui_Screen2_screen_init(void);
extern void ui_Screen2_screen_destroy(void);
extern lv_obj_t * ui_Screen2;
extern lv_obj_t * ui_home1;
extern void ui_event_toSetBtnc1(lv_event_t * e);
extern lv_obj_t * ui_toSetBtnc1;
extern void ui_event_AiAnalyzeBtnc(lv_event_t * e);
extern lv_obj_t * ui_AiAnalyzeBtnc;
extern void ui_event_ContorlBtnc(lv_event_t * e);
extern lv_obj_t * ui_ContorlBtnc;
extern lv_obj_t * ui_wenduLabel;
extern lv_obj_t * ui_zhuangsuLabel;
extern lv_obj_t * ui_shebeishuLabel;
extern lv_obj_t * ui_shiduLabel;
extern lv_obj_t * ui_zhishiLabel1;
extern lv_obj_t * ui_yonghumingLabel;
extern lv_obj_t * ui_TabView1;
extern lv_obj_t * ui_TabPage1;
extern lv_obj_t * ui_Chart1;
extern lv_chart_series_t * ui_Chart1_series_1;
extern lv_chart_series_t * ui_Chart1_series_2;
extern lv_chart_series_t * ui_Chart1_series_3;
extern lv_chart_series_t * ui_Chart1_series_4;
extern lv_obj_t * ui_TabPage2;
extern lv_obj_t * ui_Chart2;
extern lv_obj_t * ui_TabPage3;
extern lv_obj_t * ui_Arc1;
extern lv_obj_t * ui_zhishiLabel4;
extern lv_obj_t * ui_zhishiLabel2;
extern lv_obj_t * ui_zhishiLabel3;
extern lv_obj_t * ui_Dropdown1;
extern lv_obj_t * ui_Dropdown2;
extern lv_obj_t * ui_SearchBtn;
extern lv_obj_t * ui_Label1;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif