// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef UI_SCREEN1_H
#define UI_SCREEN1_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Screen1
extern void ui_Screen1_screen_init(void);
extern void ui_Screen1_screen_destroy(void);
extern lv_obj_t * ui_Screen1;
extern lv_obj_t * ui_Panel1;
extern lv_obj_t * ui_accountInput;
extern void ui_event_TextArea1(lv_event_t * e);
extern lv_obj_t * ui_TextArea1;
extern lv_obj_t * ui_Image1;
extern lv_obj_t * ui_Label2;
extern lv_obj_t * ui_passwordInput;
extern void ui_event_TextArea3(lv_event_t * e);
extern lv_obj_t * ui_TextArea3;
extern lv_obj_t * ui_Image2;
extern void ui_event_LoginBtn(lv_event_t * e);
extern lv_obj_t * ui_LoginBtn;
extern lv_obj_t * ui_Label3;
extern lv_obj_t * ui_SignUpBtn;
extern lv_obj_t * ui_Label4;
extern lv_obj_t * ui_RemberME;
extern lv_obj_t * ui_Keyboard1;
extern void ui_event_Keyboard1(lv_event_t * e);
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif