// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"
#include "utils.h"
#include <string.h>

lv_obj_t * ui_Screen1 = NULL;
lv_obj_t * ui_Panel1 = NULL;
lv_obj_t * ui_accountInput = NULL;
lv_obj_t * ui_TextArea1 = NULL;
lv_obj_t * ui_Image1 = NULL;
lv_obj_t * ui_Label2 = NULL;
lv_obj_t * ui_passwordInput = NULL;
lv_obj_t * ui_TextArea3 = NULL;
lv_obj_t * ui_Image2 = NULL;
lv_obj_t * ui_LoginBtn = NULL;
lv_obj_t * ui_Label3 = NULL;
lv_obj_t * ui_SignUpBtn = NULL;
lv_obj_t * ui_Label4 = NULL;
lv_obj_t * ui_RemberME = NULL;
lv_obj_t * ui_Keyboard1 = NULL;
// event funtions
void ui_event_TextArea1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_FOCUSED) {
        _ui_flag_modify(ui_Keyboard1, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
        lv_obj_move_foreground(ui_Keyboard1);
        _ui_keyboard_set_target(ui_Keyboard1,  ui_TextArea1);
    }
    if(event_code == LV_EVENT_DEFOCUSED) {
        _ui_flag_modify(ui_Keyboard1, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
    }
}

void ui_event_TextArea3(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_FOCUSED) {
        _ui_flag_modify(ui_Keyboard1, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
        lv_obj_move_foreground(ui_Keyboard1);
        _ui_keyboard_set_target(ui_Keyboard1,  ui_TextArea3);
    }
    if(event_code == LV_EVENT_DEFOCUSED) {
        _ui_flag_modify(ui_Keyboard1, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
    }
}

void ui_event_LoginBtn(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        if (Need_login) {
            const char *input_username = lv_textarea_get_text(ui_TextArea1);
            const char *input_password = lv_textarea_get_text(ui_TextArea3);
            
            if (strcmp(input_username, login_username) == 0 && strcmp(input_password, login_password) == 0) {
                _ui_screen_change(&ui_Screen2, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_Screen2_screen_init);
            } else {
                lv_textarea_set_text(ui_TextArea1, "");
                lv_textarea_set_text(ui_TextArea3, "");
            }
        } else {
            _ui_screen_change(&ui_Screen2, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_Screen2_screen_init);
        }
    }
}

void ui_event_Keyboard1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        lv_btnmatrix_clear_btn_ctrl_all(ui_Keyboard1, LV_BTNMATRIX_CTRL_POPOVER);
    }
}

// build funtions

void ui_Screen1_screen_init(void)
{
    ui_Screen1 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Screen1, lv_color_hex(0x1E5F81), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Screen1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_Screen1, lv_color_hex(0x183441), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_Screen1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_Screen1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_Screen1, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel1 = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_Panel1, 382);
    lv_obj_set_height(ui_Panel1, 430);
    lv_obj_set_x(ui_Panel1, 188);
    lv_obj_set_y(ui_Panel1, -7);
    lv_obj_set_align(ui_Panel1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Panel1, 25, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Panel1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_Panel1, LV_BORDER_SIDE_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_accountInput = lv_obj_create(ui_Panel1);
    lv_obj_set_width(ui_accountInput, 341);
    lv_obj_set_height(ui_accountInput, 53);
    lv_obj_set_x(ui_accountInput, -1);
    lv_obj_set_y(ui_accountInput, -100);
    lv_obj_set_align(ui_accountInput, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_accountInput, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_TextArea1 = lv_textarea_create(ui_accountInput);
    lv_obj_set_width(ui_TextArea1, 286);
    lv_obj_set_height(ui_TextArea1, 43);
    lv_obj_set_x(ui_TextArea1, 24);
    lv_obj_set_y(ui_TextArea1, 0);
    lv_obj_set_align(ui_TextArea1, LV_ALIGN_CENTER);
    lv_textarea_set_placeholder_text(ui_TextArea1, "Placeholder...");
    lv_obj_set_style_border_color(ui_TextArea1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_TextArea1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image1 = lv_img_create(ui_accountInput);
    lv_img_set_src(ui_Image1, &ui_img_accounticon_png_png);
    lv_obj_set_width(ui_Image1, LV_SIZE_CONTENT);   /// 50
    lv_obj_set_height(ui_Image1, LV_SIZE_CONTENT);    /// 53
    lv_obj_set_x(ui_Image1, -145);
    lv_obj_set_y(ui_Image1, 0);
    lv_obj_set_align(ui_Image1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image1, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_Image1, 200);

    ui_Label2 = lv_label_create(ui_Panel1);
    lv_obj_set_width(ui_Label2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label2, 0);
    lv_obj_set_y(ui_Label2, -180);
    lv_obj_set_align(ui_Label2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label2, "Login");
    lv_obj_set_style_text_color(ui_Label2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label2, &lv_font_montserrat_40, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_passwordInput = lv_obj_create(ui_Panel1);
    lv_obj_set_width(ui_passwordInput, 341);
    lv_obj_set_height(ui_passwordInput, 53);
    lv_obj_set_x(ui_passwordInput, -2);
    lv_obj_set_y(ui_passwordInput, -29);
    lv_obj_set_align(ui_passwordInput, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_passwordInput, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_TextArea3 = lv_textarea_create(ui_passwordInput);
    lv_obj_set_width(ui_TextArea3, 286);
    lv_obj_set_height(ui_TextArea3, 43);
    lv_obj_set_x(ui_TextArea3, 24);
    lv_obj_set_y(ui_TextArea3, 0);
    lv_obj_set_align(ui_TextArea3, LV_ALIGN_CENTER);
    lv_textarea_set_placeholder_text(ui_TextArea3, "Placeholder...");
    lv_obj_set_style_border_color(ui_TextArea3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_TextArea3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image2 = lv_img_create(ui_passwordInput);
    lv_img_set_src(ui_Image2, &ui_img_loginicon_png);
    lv_obj_set_width(ui_Image2, LV_SIZE_CONTENT);   /// 50
    lv_obj_set_height(ui_Image2, LV_SIZE_CONTENT);    /// 53
    lv_obj_set_x(ui_Image2, -145);
    lv_obj_set_y(ui_Image2, -1);
    lv_obj_set_align(ui_Image2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image2, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_Image2, 130);

    ui_LoginBtn = lv_btn_create(ui_Panel1);
    lv_obj_set_width(ui_LoginBtn, 338);
    lv_obj_set_height(ui_LoginBtn, 50);
    lv_obj_set_x(ui_LoginBtn, -2);
    lv_obj_set_y(ui_LoginBtn, 68);
    lv_obj_set_align(ui_LoginBtn, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_LoginBtn, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_LoginBtn, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_LoginBtn, lv_color_hex(0x3DABEE), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_LoginBtn, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label3 = lv_label_create(ui_LoginBtn);
    lv_obj_set_width(ui_Label3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label3, "Sign In");
    lv_obj_set_style_text_color(ui_Label3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label3, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SignUpBtn = lv_btn_create(ui_Panel1);
    lv_obj_set_width(ui_SignUpBtn, 100);
    lv_obj_set_height(ui_SignUpBtn, 31);
    lv_obj_set_x(ui_SignUpBtn, -122);
    lv_obj_set_y(ui_SignUpBtn, 20);
    lv_obj_set_align(ui_SignUpBtn, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_SignUpBtn, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_SignUpBtn, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_SignUpBtn, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SignUpBtn, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_SignUpBtn, LV_BORDER_SIDE_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_SignUpBtn, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_SignUpBtn, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_SignUpBtn, lv_color_hex(0xEEEEEE), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_opa(ui_SignUpBtn, 255, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_Label4 = lv_label_create(ui_SignUpBtn);
    lv_obj_set_width(ui_Label4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label4, -14);
    lv_obj_set_y(ui_Label4, 0);
    lv_obj_set_align(ui_Label4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label4, "Sign Up");
    lv_obj_set_style_text_color(ui_Label4, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_RemberME = lv_checkbox_create(ui_Panel1);
    lv_checkbox_set_text(ui_RemberME, "Remeber Me");
    lv_obj_set_width(ui_RemberME, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_RemberME, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_RemberME, 105);
    lv_obj_set_y(ui_RemberME, 21);
    lv_obj_set_align(ui_RemberME, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_RemberME, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags

    ui_Keyboard1 = lv_keyboard_create(ui_Screen1);
    lv_obj_set_width(ui_Keyboard1, 802);
    lv_obj_set_height(ui_Keyboard1, 237);
    lv_obj_set_x(ui_Keyboard1, 0);
    lv_obj_set_y(ui_Keyboard1, 118);
    lv_obj_set_align(ui_Keyboard1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Keyboard1, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_keyboard_set_popovers(ui_Keyboard1, false);          /// 禁用按键大字弹窗
    lv_btnmatrix_clear_btn_ctrl_all(ui_Keyboard1, LV_BTNMATRIX_CTRL_POPOVER);  /// 直接清除按键控制位

    lv_obj_add_event_cb(ui_TextArea1, ui_event_TextArea1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_TextArea3, ui_event_TextArea3, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_LoginBtn, ui_event_LoginBtn, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Keyboard1, ui_event_Keyboard1, LV_EVENT_ALL, NULL);

}

void ui_Screen1_screen_destroy(void)
{
    if(ui_Screen1) lv_obj_del(ui_Screen1);

    // NULL screen variables
    ui_Screen1 = NULL;
    ui_Panel1 = NULL;
    ui_accountInput = NULL;
    ui_TextArea1 = NULL;
    ui_Image1 = NULL;
    ui_Label2 = NULL;
    ui_passwordInput = NULL;
    ui_TextArea3 = NULL;
    ui_Image2 = NULL;
    ui_LoginBtn = NULL;
    ui_Label3 = NULL;
    ui_SignUpBtn = NULL;
    ui_Label4 = NULL;
    ui_RemberME = NULL;
    ui_Keyboard1 = NULL;

}