// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"
#include "utils.h"

// 从utils.h中引入Screen5的全局变量
extern char Screen5_wifi_status_text[32];
extern char Screen5_ip_addr_text[40];
extern char Screen5_api_url_text[64];
extern char Screen5_api_key_text[32];
extern char Screen5_cpu_usage_text[10];
extern char Screen5_stack_usage_text[10];
extern char Screen5_auto_save_time_text[32];

lv_obj_t * ui_Screen5 = NULL;
lv_obj_t * ui_Image5 = NULL;
lv_obj_t * ui_KeyboardSc5 = NULL;
lv_obj_t * ui_WifiNameInp = NULL;
lv_obj_t * ui_WifipswordInp = NULL;
lv_obj_t * ui_IpInp = NULL;
lv_obj_t * ui_UDPInp = NULL;
lv_obj_t * ui_BackBtnc = NULL;
lv_obj_t * ui_SaveAllBtnc = NULL;
lv_obj_t * ui_PingBtnc1 = NULL;
lv_obj_t * ui_PingBtnc2 = NULL;
// Screen5 新增文本标签
lv_obj_t * ui_WifiStatusLabel = NULL;
lv_obj_t * ui_IpAddrLabel = NULL;
lv_obj_t * ui_ApiUrlLabel = NULL;
lv_obj_t * ui_ApiKeyLabel = NULL;
lv_obj_t * ui_CpuUsageLabel = NULL;
lv_obj_t * ui_StackUsageLabel = NULL;
lv_obj_t * ui_AutoSaveTimeLabel = NULL;
// event funtions
void ui_event_WifiNameInp(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_FOCUSED) {
        _ui_flag_modify(ui_KeyboardSc5, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
    }
    if(event_code == LV_EVENT_DEFOCUSED) {
        _ui_flag_modify(ui_KeyboardSc5, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
    }
    if(event_code == LV_EVENT_FOCUSED) {
        _ui_keyboard_set_target(ui_KeyboardSc5,  ui_WifiNameInp);
    }
}

void ui_event_WifipswordInp(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_FOCUSED) {
        _ui_flag_modify(ui_KeyboardSc5, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
    }
    if(event_code == LV_EVENT_DEFOCUSED) {
        _ui_flag_modify(ui_KeyboardSc5, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
    }
    if(event_code == LV_EVENT_FOCUSED) {
        _ui_keyboard_set_target(ui_KeyboardSc5,  ui_WifipswordInp);
    }
}

void ui_event_IpInp(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_FOCUSED) {
        _ui_flag_modify(ui_KeyboardSc5, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
    }
    if(event_code == LV_EVENT_DEFOCUSED) {
        _ui_flag_modify(ui_KeyboardSc5, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
    }
    if(event_code == LV_EVENT_FOCUSED) {
        _ui_keyboard_set_target(ui_KeyboardSc5,  ui_IpInp);
    }
}

void ui_event_UDPInp(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_FOCUSED) {
        _ui_flag_modify(ui_KeyboardSc5, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
    }
    if(event_code == LV_EVENT_DEFOCUSED) {
        _ui_flag_modify(ui_KeyboardSc5, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
    }
    if(event_code == LV_EVENT_FOCUSED) {
        _ui_keyboard_set_target(ui_KeyboardSc5,  ui_UDPInp);
    }
}

void ui_event_BackBtnc(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Screen2, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_Screen2_screen_init);
    }
}

void ui_event_SaveAllBtnc(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Screen2, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_Screen2_screen_init);
    }
}

void ui_event_PingBtnc1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Screen2, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_Screen2_screen_init);
    }
}

void ui_event_PingBtnc2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Screen2, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_Screen2_screen_init);
    }
}

void ui_event_KeyboardSc5(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        lv_btnmatrix_clear_btn_ctrl_all(ui_KeyboardSc5, LV_BTNMATRIX_CTRL_POPOVER);
    }
}

// build funtions

void ui_Screen5_screen_init(void)
{
    ui_Screen5 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image5 = lv_img_create(ui_Screen5);
    lv_img_set_src(ui_Image5, &ui_img_home4_png);
    lv_obj_set_width(ui_Image5, 800);
    lv_obj_set_height(ui_Image5, 480);
    lv_obj_set_align(ui_Image5, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image5, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_Image5, 259);

    ui_KeyboardSc5 = lv_keyboard_create(ui_Screen5);
    lv_obj_set_width(ui_KeyboardSc5, 799);
    lv_obj_set_height(ui_KeyboardSc5, 257);
    lv_obj_set_x(ui_KeyboardSc5, -2);
    lv_obj_set_y(ui_KeyboardSc5, 116);
    lv_obj_set_align(ui_KeyboardSc5, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_KeyboardSc5, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_keyboard_set_popovers(ui_KeyboardSc5, false);
    lv_btnmatrix_clear_btn_ctrl_all(ui_KeyboardSc5, LV_BTNMATRIX_CTRL_POPOVER);

    ui_WifiNameInp = lv_textarea_create(ui_Screen5);
    lv_obj_set_width(ui_WifiNameInp, 285);
    lv_obj_set_height(ui_WifiNameInp, 40);
    lv_obj_set_x(ui_WifiNameInp, -141);
    lv_obj_set_y(ui_WifiNameInp, -99);
    lv_obj_set_align(ui_WifiNameInp, LV_ALIGN_CENTER);
    lv_textarea_set_placeholder_text(ui_WifiNameInp, "Input WiFi Name...");
    lv_textarea_set_text(ui_WifiNameInp, "JIGE666");
    lv_obj_set_style_text_color(ui_WifiNameInp, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_WifiNameInp, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_WifiNameInp, lv_color_hex(0x202C31), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_WifiNameInp, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_WifiNameInp, lv_color_hex(0x5A5D62), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_WifiNameInp, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_WifipswordInp = lv_textarea_create(ui_Screen5);
    lv_obj_set_width(ui_WifipswordInp, 285);
    lv_obj_set_height(ui_WifipswordInp, 40);
    lv_obj_set_x(ui_WifipswordInp, -142);
    lv_obj_set_y(ui_WifipswordInp, -54);
    lv_obj_set_align(ui_WifipswordInp, LV_ALIGN_CENTER);
    lv_textarea_set_placeholder_text(ui_WifipswordInp, "Input Password...");
    lv_textarea_set_text(ui_WifipswordInp, "12345678");
    // 设置密码输入模式
    lv_textarea_set_password_mode(ui_WifipswordInp, true);
    lv_obj_set_style_text_color(ui_WifipswordInp, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_WifipswordInp, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_WifipswordInp, lv_color_hex(0x202C31), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_WifipswordInp, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_WifipswordInp, lv_color_hex(0x5A5D62), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_WifipswordInp, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_IpInp = lv_textarea_create(ui_Screen5);
    lv_obj_set_width(ui_IpInp, 266);
    lv_obj_set_height(ui_IpInp, 40);
    lv_obj_set_x(ui_IpInp, 239);
    lv_obj_set_y(ui_IpInp, -104);
    lv_obj_set_align(ui_IpInp, LV_ALIGN_CENTER);
    lv_textarea_set_placeholder_text(ui_IpInp, "Input IP Address...");
    lv_textarea_set_text(ui_IpInp, "192.168.1.100");
    lv_obj_set_style_text_color(ui_IpInp, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_IpInp, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_IpInp, lv_color_hex(0x202C31), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_IpInp, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_IpInp, lv_color_hex(0x5A5D62), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_IpInp, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_UDPInp = lv_textarea_create(ui_Screen5);
    lv_obj_set_width(ui_UDPInp, 266);
    lv_obj_set_height(ui_UDPInp, 40);
    lv_obj_set_x(ui_UDPInp, 239);
    lv_obj_set_y(ui_UDPInp, -57);
    lv_obj_set_align(ui_UDPInp, LV_ALIGN_CENTER);
    lv_textarea_set_placeholder_text(ui_UDPInp, "Input UDP Port...");
    lv_textarea_set_text(ui_UDPInp, "8080");
    lv_obj_set_style_text_color(ui_UDPInp, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_UDPInp, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_UDPInp, lv_color_hex(0x202C31), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_UDPInp, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_UDPInp, lv_color_hex(0x5A5D62), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_UDPInp, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BackBtnc = lv_obj_create(ui_Screen5);
    lv_obj_remove_style_all(ui_BackBtnc);
    lv_obj_set_width(ui_BackBtnc, 58);
    lv_obj_set_height(ui_BackBtnc, 57);
    lv_obj_set_x(ui_BackBtnc, -358);
    lv_obj_set_y(ui_BackBtnc, -196);
    lv_obj_set_align(ui_BackBtnc, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_BackBtnc, LV_OBJ_FLAG_CLICKABLE);
    lv_obj_clear_flag(ui_BackBtnc, LV_OBJ_FLAG_SCROLLABLE);

    ui_SaveAllBtnc = lv_obj_create(ui_Screen5);
    lv_obj_remove_style_all(ui_SaveAllBtnc);
    lv_obj_set_width(ui_SaveAllBtnc, 123);
    lv_obj_set_height(ui_SaveAllBtnc, 46);
    lv_obj_set_x(ui_SaveAllBtnc, 328);
    lv_obj_set_y(ui_SaveAllBtnc, -200);
    lv_obj_set_align(ui_SaveAllBtnc, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_SaveAllBtnc, LV_OBJ_FLAG_CLICKABLE);
    lv_obj_clear_flag(ui_SaveAllBtnc, LV_OBJ_FLAG_SCROLLABLE);

    ui_PingBtnc1 = lv_obj_create(ui_Screen5);
    lv_obj_remove_style_all(ui_PingBtnc1);
    lv_obj_set_width(ui_PingBtnc1, 65);
    lv_obj_set_height(ui_PingBtnc1, 33);
    lv_obj_set_x(ui_PingBtnc1, -200);
    lv_obj_set_y(ui_PingBtnc1, 203);
    lv_obj_set_align(ui_PingBtnc1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_PingBtnc1, LV_OBJ_FLAG_CLICKABLE);
    lv_obj_clear_flag(ui_PingBtnc1, LV_OBJ_FLAG_SCROLLABLE);

    ui_PingBtnc2 = lv_obj_create(ui_Screen5);
    lv_obj_remove_style_all(ui_PingBtnc2);
    lv_obj_set_width(ui_PingBtnc2, 65);
    lv_obj_set_height(ui_PingBtnc2, 33);
    lv_obj_set_x(ui_PingBtnc2, 340);
    lv_obj_set_y(ui_PingBtnc2, -12);
    lv_obj_set_align(ui_PingBtnc2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_PingBtnc2, LV_OBJ_FLAG_CLICKABLE);
    lv_obj_clear_flag(ui_PingBtnc2, LV_OBJ_FLAG_SCROLLABLE);

// 文本内容 ---------------------------------------------------------------

    // WiFi连接状态
    ui_WifiStatusLabel = lv_label_create(ui_Screen5);
    lv_obj_set_pos(ui_WifiStatusLabel, 120, 220+10); 
    lv_obj_set_size(ui_WifiStatusLabel, 276, 25);
    lv_label_set_text(ui_WifiStatusLabel, Screen5_wifi_status_text);
    lv_obj_set_style_text_color(ui_WifiStatusLabel, lv_color_white(), LV_PART_MAIN);
    lv_obj_set_style_text_font(ui_WifiStatusLabel, &lv_font_montserrat_12, LV_PART_MAIN);  // 设置字体大小12

    // 本机IP地址
    ui_IpAddrLabel = lv_label_create(ui_Screen5);
    lv_obj_set_pos(ui_IpAddrLabel, 522, 218+10); 
    lv_obj_set_size(ui_IpAddrLabel, 170, 31);
    lv_label_set_text(ui_IpAddrLabel, Screen5_ip_addr_text);
    lv_obj_set_style_text_color(ui_IpAddrLabel, lv_color_white(), LV_PART_MAIN);
    lv_obj_set_style_text_font(ui_IpAddrLabel, &lv_font_montserrat_12, LV_PART_MAIN);

    // API地址
    ui_ApiUrlLabel = lv_label_create(ui_Screen5);
    lv_obj_set_pos(ui_ApiUrlLabel, 30, 325); 
    lv_obj_set_size(ui_ApiUrlLabel, 195, 25);
    lv_label_set_text(ui_ApiUrlLabel, Screen5_api_url_text);
    lv_obj_set_style_text_color(ui_ApiUrlLabel, lv_color_white(), LV_PART_MAIN);
    lv_obj_set_style_text_font(ui_ApiUrlLabel, &lv_font_montserrat_12, LV_PART_MAIN);

    // API密钥
    ui_ApiKeyLabel = lv_label_create(ui_Screen5);
    lv_obj_set_pos(ui_ApiKeyLabel, 30, 379); 
    lv_obj_set_size(ui_ApiKeyLabel, 198, 24);
    lv_label_set_text(ui_ApiKeyLabel, Screen5_api_key_text);
    lv_obj_set_style_text_color(ui_ApiKeyLabel, lv_color_white(), LV_PART_MAIN);
    lv_obj_set_style_text_font(ui_ApiKeyLabel, &lv_font_montserrat_12, LV_PART_MAIN);

    // CPU占用
    ui_CpuUsageLabel = lv_label_create(ui_Screen5);
    lv_obj_set_pos(ui_CpuUsageLabel, 601, 294+10); 
    lv_obj_set_size(ui_CpuUsageLabel, 175, 21);
    lv_label_set_text(ui_CpuUsageLabel, Screen5_cpu_usage_text);
    lv_obj_set_style_text_color(ui_CpuUsageLabel, lv_color_white(), LV_PART_MAIN);
    lv_obj_set_style_text_font(ui_CpuUsageLabel, &lv_font_montserrat_12, LV_PART_MAIN);

    // 堆栈占用
    ui_StackUsageLabel = lv_label_create(ui_Screen5);
    lv_obj_set_pos(ui_StackUsageLabel, 601, 319+10); 
    lv_obj_set_size(ui_StackUsageLabel, 175, 25);
    lv_label_set_text(ui_StackUsageLabel, Screen5_stack_usage_text);
    lv_obj_set_style_text_color(ui_StackUsageLabel, lv_color_white(), LV_PART_MAIN);
    lv_obj_set_style_text_font(ui_StackUsageLabel, &lv_font_montserrat_12, LV_PART_MAIN);

    // 自动保存时间
    ui_AutoSaveTimeLabel = lv_label_create(ui_Screen5);
    lv_obj_set_pos(ui_AutoSaveTimeLabel, 636, 425+15); // 直接填入编辑器里的 X, Y
    lv_obj_set_size(ui_AutoSaveTimeLabel, 140, 32);
    lv_label_set_text(ui_AutoSaveTimeLabel, Screen5_auto_save_time_text);
    lv_obj_set_style_text_color(ui_AutoSaveTimeLabel, lv_color_white(), LV_PART_MAIN);
    lv_obj_set_style_text_font(ui_AutoSaveTimeLabel, &lv_font_montserrat_12, LV_PART_MAIN);

    // 重新注册事件回调
    lv_obj_add_event_cb(ui_WifiNameInp, ui_event_WifiNameInp, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_WifipswordInp, ui_event_WifipswordInp, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_IpInp, ui_event_IpInp, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_UDPInp, ui_event_UDPInp, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_BackBtnc, ui_event_BackBtnc, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_SaveAllBtnc, ui_event_SaveAllBtnc, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_PingBtnc1, ui_event_PingBtnc1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_PingBtnc2, ui_event_PingBtnc2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_KeyboardSc5, ui_event_KeyboardSc5, LV_EVENT_ALL, NULL);
}

void ui_Screen5_screen_destroy(void)
{
    if(ui_Screen5) lv_obj_del(ui_Screen5);

    // NULL screen variables
    ui_Screen5 = NULL;
    ui_Image5 = NULL;
    ui_KeyboardSc5 = NULL;
    ui_WifiNameInp = NULL;
    ui_WifipswordInp = NULL;
    ui_IpInp = NULL;
    ui_UDPInp = NULL;
    ui_BackBtnc = NULL;
    ui_SaveAllBtnc = NULL;
    ui_PingBtnc1 = NULL;
    ui_PingBtnc2 = NULL;
    // Screen5 新增标签
    ui_WifiStatusLabel = NULL;
    ui_IpAddrLabel = NULL;
    ui_ApiUrlLabel = NULL;
    ui_ApiKeyLabel = NULL;
    ui_CpuUsageLabel = NULL;
    ui_StackUsageLabel = NULL;
    ui_AutoSaveTimeLabel = NULL;

}