// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef UI_SCREEN5_H
#define UI_SCREEN5_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Screen5
extern void ui_Screen5_screen_init(void);
extern void ui_Screen5_screen_destroy(void);
extern lv_obj_t * ui_Screen5;
extern lv_obj_t * ui_Image5;
extern lv_obj_t * ui_KeyboardSc5;
extern void ui_event_KeyboardSc5(lv_event_t * e);
extern void ui_event_WifiNameInp(lv_event_t * e);
extern lv_obj_t * ui_WifiNameInp;
extern void ui_event_WifipswordInp(lv_event_t * e);
extern lv_obj_t * ui_WifipswordInp;
extern void ui_event_IpInp(lv_event_t * e);
extern lv_obj_t * ui_IpInp;
extern void ui_event_UDPInp(lv_event_t * e);
extern lv_obj_t * ui_UDPInp;
extern void ui_event_BackBtnc(lv_event_t * e);
extern lv_obj_t * ui_BackBtnc;
extern void ui_event_SaveAllBtnc(lv_event_t * e);
extern lv_obj_t * ui_SaveAllBtnc;
extern void ui_event_PingBtnc1(lv_event_t * e);
extern lv_obj_t * ui_PingBtnc1;
extern void ui_event_PingBtnc2(lv_event_t * e);
extern lv_obj_t * ui_PingBtnc2;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif