// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"
#include "utils.h"
#include "../uart/uart.h"
#include "freertos/task.h"
#include "freertos/FreeRTOS.h"

lv_obj_t * ui_Screen2 = NULL;
lv_obj_t * ui_home1 = NULL;
lv_obj_t * ui_toSetBtnc1 = NULL;
lv_obj_t * ui_AiAnalyzeBtnc = NULL;
lv_obj_t * ui_ContorlBtnc = NULL;
lv_obj_t * ui_toChatBtnc1 = NULL;
lv_obj_t * ui_wenduLabel = NULL;
lv_obj_t * ui_zhuangsuLabel = NULL;
lv_obj_t * ui_shebeishuLabel = NULL;
lv_obj_t * ui_shiduLabel = NULL;
lv_obj_t * ui_zhishiLabel1 = NULL;
lv_obj_t * ui_yonghumingLabel = NULL;
lv_obj_t * ui_TabView1 = NULL;
lv_obj_t * ui_TabPage1 = NULL;
lv_obj_t * ui_Chart1 = NULL;
lv_obj_t * ui_TabPage2 = NULL;
lv_obj_t * ui_Chart2 = NULL;
lv_obj_t * ui_TabPage3 = NULL;
lv_obj_t * ui_Arc1 = NULL;
lv_obj_t * ui_zhishiLabel4 = NULL;
lv_obj_t * ui_zhishiLabel2 = NULL;
lv_obj_t * ui_zhishiLabel3 = NULL;
lv_obj_t * ui_Dropdown1 = NULL;
lv_obj_t * ui_Dropdown2 = NULL;
lv_obj_t * ui_SearchBtn = NULL;
lv_obj_t * ui_Label1 = NULL;

lv_chart_series_t * ui_Chart1_series_1 = NULL;
lv_chart_series_t * ui_Chart1_series_2 = NULL;
lv_chart_series_t * ui_Chart1_series_3 = NULL;
lv_chart_series_t * ui_Chart1_series_4 = NULL;

lv_chart_series_t * ui_Chart2_series_1 = NULL;
lv_chart_series_t * ui_Chart2_series_2 = NULL;

// 从utils.h中引入Temperature、Humidity、sound_level、jitter_level
extern float Temperature;
extern float Humidity;
extern uint16_t sound_level;
extern uint8_t jitter_level;
extern char Instruction_text[];
extern char user_name[];

// 从utils.h中引入图表数据数组
extern lv_coord_t ui_Chart1_series_1_array[];
extern lv_coord_t ui_Chart1_series_2_array[];
extern lv_coord_t ui_Chart1_series_3_array[];
extern lv_coord_t ui_Chart1_series_4_array[];
extern lv_coord_t ui_Chart2_series_1_array[];
extern lv_coord_t ui_Chart2_series_2_array[];

// event funtions
void ui_event_toSetBtnc1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Screen5, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_Screen5_screen_init);
    }
}

void ui_event_AiAnalyzeBtnc(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Screen3, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_Screen3_screen_init);
    }
}

void ui_event_ContorlBtnc(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Screen4, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_Screen4_screen_init);
    }
}

void ui_event_toChatBtnc1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Screen3, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_Screen3_screen_init);
    }
}

// build funtions

void ui_Screen2_screen_init(void)
{
    ui_Screen2 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_home1 = lv_img_create(ui_Screen2);
    lv_img_set_src(ui_home1, &ui_img_home1_png);
    lv_obj_set_width(ui_home1, LV_SIZE_CONTENT);   /// 800
    lv_obj_set_height(ui_home1, LV_SIZE_CONTENT);    /// 477
    lv_obj_set_x(ui_home1, 0);
    lv_obj_set_y(ui_home1, 0);
    lv_obj_set_align(ui_home1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_home1, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_home1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    // lv_img_set_zoom(ui_home1, 137);

    ui_toSetBtnc1 = lv_obj_create(ui_Screen2);
    lv_obj_remove_style_all(ui_toSetBtnc1);
    lv_obj_set_width(ui_toSetBtnc1, 173);
    lv_obj_set_height(ui_toSetBtnc1, 50);
    lv_obj_set_x(ui_toSetBtnc1, -114);
    lv_obj_set_y(ui_toSetBtnc1, -200);
    lv_obj_set_align(ui_toSetBtnc1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_toSetBtnc1, LV_OBJ_FLAG_CLICKABLE);
    lv_obj_clear_flag(ui_toSetBtnc1, LV_OBJ_FLAG_SCROLLABLE);

    ui_AiAnalyzeBtnc = lv_obj_create(ui_Screen2);
    lv_obj_remove_style_all(ui_AiAnalyzeBtnc);
    lv_obj_set_width(ui_AiAnalyzeBtnc, 162);
    lv_obj_set_height(ui_AiAnalyzeBtnc, 50);
    lv_obj_set_x(ui_AiAnalyzeBtnc, 97);
    lv_obj_set_y(ui_AiAnalyzeBtnc, 196);
    lv_obj_set_align(ui_AiAnalyzeBtnc, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_AiAnalyzeBtnc, LV_OBJ_FLAG_CLICKABLE);
    lv_obj_clear_flag(ui_AiAnalyzeBtnc, LV_OBJ_FLAG_SCROLLABLE);

    ui_ContorlBtnc = lv_obj_create(ui_Screen2);
    lv_obj_remove_style_all(ui_ContorlBtnc);
    lv_obj_set_width(ui_ContorlBtnc, 177);
    lv_obj_set_height(ui_ContorlBtnc, 50);
    lv_obj_set_x(ui_ContorlBtnc, 295);
    lv_obj_set_y(ui_ContorlBtnc, 198);
    lv_obj_set_align(ui_ContorlBtnc, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ContorlBtnc, LV_OBJ_FLAG_CLICKABLE);
    lv_obj_clear_flag(ui_ContorlBtnc, LV_OBJ_FLAG_SCROLLABLE);

    ui_toChatBtnc1 = lv_obj_create(ui_Screen2);
    lv_obj_remove_style_all(ui_toChatBtnc1);
    lv_obj_set_width(ui_toChatBtnc1, 57);
    lv_obj_set_height(ui_toChatBtnc1, 59);
    lv_obj_set_x(ui_toChatBtnc1, 354);
    lv_obj_set_y(ui_toChatBtnc1, -197);
    lv_obj_set_align(ui_toChatBtnc1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_toChatBtnc1, LV_OBJ_FLAG_CLICKABLE);
    lv_obj_clear_flag(ui_toChatBtnc1, LV_OBJ_FLAG_SCROLLABLE);

    // 温度标签
    ui_wenduLabel = lv_label_create(ui_Screen2);
    lv_obj_set_width(ui_wenduLabel, 121);
    lv_obj_set_height(ui_wenduLabel, 60);
    lv_obj_set_x(ui_wenduLabel, 106);
    lv_obj_set_y(ui_wenduLabel, -45);
    lv_obj_set_align(ui_wenduLabel, LV_ALIGN_CENTER); 
    lv_label_set_text(ui_wenduLabel, safe_ftoa_1d(Temperature));  // 显示温度
    lv_obj_set_style_text_color(ui_wenduLabel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_wenduLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_wenduLabel, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_wenduLabel, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);

    // 声源大小标签
    ui_zhuangsuLabel = lv_label_create(ui_Screen2);
    lv_obj_set_width(ui_zhuangsuLabel, 121);
    lv_obj_set_height(ui_zhuangsuLabel, 60);
    lv_obj_set_x(ui_zhuangsuLabel, 100);
    lv_obj_set_y(ui_zhuangsuLabel, 104);
    lv_obj_set_align(ui_zhuangsuLabel, LV_ALIGN_CENTER);
    snprintf(g_value_str, sizeof(g_value_str), "%u", sound_level);
    lv_label_set_text(ui_zhuangsuLabel, g_value_str);
    lv_obj_set_style_text_color(ui_zhuangsuLabel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_zhuangsuLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_zhuangsuLabel, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_zhuangsuLabel, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);

    // 抖动程度标签
    ui_shebeishuLabel = lv_label_create(ui_Screen2);
    lv_obj_set_width(ui_shebeishuLabel, 121);
    lv_obj_set_height(ui_shebeishuLabel, 60);
    lv_obj_set_x(ui_shebeishuLabel, 289);
    lv_obj_set_y(ui_shebeishuLabel, 104);
    lv_obj_set_align(ui_shebeishuLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_shebeishuLabel, safe_utoa(jitter_level));
    lv_obj_set_style_text_color(ui_shebeishuLabel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_shebeishuLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_shebeishuLabel, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_shebeishuLabel, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);

    // 湿度标签
    ui_shiduLabel = lv_label_create(ui_Screen2);
    lv_obj_set_width(ui_shiduLabel, 107);
    lv_obj_set_height(ui_shiduLabel, 60);
    lv_obj_set_x(ui_shiduLabel, 281);
    lv_obj_set_y(ui_shiduLabel, -42);
    lv_obj_set_align(ui_shiduLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_shiduLabel, safe_ftoa_1d(Humidity));
    lv_obj_set_style_text_color(ui_shiduLabel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_shiduLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_shiduLabel, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_shiduLabel, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);

    // 指示文本标签
    ui_zhishiLabel1 = lv_label_create(ui_Screen2);
    lv_obj_set_width(ui_zhishiLabel1, 206);
    lv_obj_set_height(ui_zhishiLabel1, 35);
    lv_obj_set_x(ui_zhishiLabel1, 141);
    lv_obj_set_y(ui_zhishiLabel1, -200);
    lv_obj_set_align(ui_zhishiLabel1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_zhishiLabel1, Instruction_text);
    lv_obj_set_style_text_color(ui_zhishiLabel1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_zhishiLabel1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_zhishiLabel1, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_zhishiLabel1, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    // 用户名标签
    ui_yonghumingLabel = lv_label_create(ui_Screen2);
    lv_obj_set_width(ui_yonghumingLabel, 112);
    lv_obj_set_height(ui_yonghumingLabel, 33);
    lv_obj_set_x(ui_yonghumingLabel, -282);
    lv_obj_set_y(ui_yonghumingLabel, -199);
    lv_obj_set_align(ui_yonghumingLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_yonghumingLabel, user_name);
    lv_obj_set_style_text_color(ui_yonghumingLabel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_yonghumingLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_yonghumingLabel, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_yonghumingLabel, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TabView1 = lv_tabview_create(ui_Screen2, LV_DIR_TOP, 50);
    lv_obj_set_width(ui_TabView1, 417);
    lv_obj_set_height(ui_TabView1, 298);
    lv_obj_set_x(ui_TabView1, -181);
    lv_obj_set_y(ui_TabView1, -15);
    lv_obj_set_align(ui_TabView1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_TabView1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_TabView1, 20, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(lv_tabview_get_tab_btns(ui_TabView1), 20,  LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(lv_tabview_get_tab_btns(ui_TabView1), 0,  LV_PART_ITEMS | LV_STATE_DEFAULT);

    ui_TabPage1 = lv_tabview_add_tab(ui_TabView1, "I-U-RMP");
    lv_obj_clear_flag(ui_TabPage1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Chart2 = lv_chart_create(ui_TabPage1);
    lv_obj_set_width(ui_Chart2, 360);
    lv_obj_set_height(ui_Chart2, 201);
    lv_obj_set_x(ui_Chart2, 15);
    lv_obj_set_y(ui_Chart2, -14);
    lv_obj_set_align(ui_Chart2, LV_ALIGN_CENTER);
    lv_chart_set_type(ui_Chart2, LV_CHART_TYPE_BAR);
    lv_chart_set_axis_tick(ui_Chart2, LV_CHART_AXIS_PRIMARY_X, 10, 5, 5, 2, true, 50);
    lv_chart_set_axis_tick(ui_Chart2, LV_CHART_AXIS_PRIMARY_Y, 10, 5, 5, 2, true, 50);
    lv_chart_set_axis_tick(ui_Chart2, LV_CHART_AXIS_SECONDARY_Y, 0, 0, 0, 0, false, 25);
    lv_chart_set_range(ui_Chart2, LV_CHART_AXIS_PRIMARY_Y, 0, 5000);     // 0.00~50.00mA (×100)
    lv_chart_set_range(ui_Chart2, LV_CHART_AXIS_SECONDARY_Y, 2400, 3000); // 24.00~30.00V (×100)
    ui_Chart2_series_1 = lv_chart_add_series(ui_Chart2, lv_color_hex(0xED3B67),
                                              LV_CHART_AXIS_PRIMARY_Y);
    lv_chart_set_ext_y_array(ui_Chart2, ui_Chart2_series_1, ui_Chart2_series_1_array);
    ui_Chart2_series_2 = lv_chart_add_series(ui_Chart2, lv_color_hex(0xECCFCF),
                                              LV_CHART_AXIS_SECONDARY_Y);
    lv_chart_set_ext_y_array(ui_Chart2, ui_Chart2_series_2, ui_Chart2_series_2_array);

    lv_obj_set_style_text_color(ui_Chart2, lv_color_hex(0x000000), LV_PART_TICKS | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Chart2, 255, LV_PART_TICKS | LV_STATE_DEFAULT);

    ui_TabPage2 = lv_tabview_add_tab(ui_TabView1, "Accel");
    lv_obj_clear_flag(ui_TabPage2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Chart1 = lv_chart_create(ui_TabPage2);
    lv_obj_set_width(ui_Chart1, 360);
    lv_obj_set_height(ui_Chart1, 204);
    lv_obj_set_x(ui_Chart1, 12);
    lv_obj_set_y(ui_Chart1, -9);
    lv_obj_set_align(ui_Chart1, LV_ALIGN_CENTER);
    lv_chart_set_type(ui_Chart1, LV_CHART_TYPE_LINE);
    lv_chart_set_point_count(ui_Chart1, 20);
    lv_chart_set_zoom_x(ui_Chart1, 300);
    lv_chart_set_zoom_y(ui_Chart1, 256);
    lv_chart_set_range(ui_Chart1, LV_CHART_AXIS_PRIMARY_Y, -50, 50);
    lv_chart_set_range(ui_Chart1, LV_CHART_AXIS_SECONDARY_Y, 700, 900);
    lv_chart_set_axis_tick(ui_Chart1, LV_CHART_AXIS_PRIMARY_X, 10, 5, 5, 2, true, 50);
    lv_chart_set_axis_tick(ui_Chart1, LV_CHART_AXIS_PRIMARY_Y, 10, 5, 11, 2, true, 50);
    lv_chart_set_axis_tick(ui_Chart1, LV_CHART_AXIS_SECONDARY_Y, 0, 0, 0, 0, false, 25);
    ui_Chart1_series_1 = lv_chart_add_series(ui_Chart1, lv_color_hex(0x4FA4F6), LV_CHART_AXIS_PRIMARY_Y);
    lv_chart_set_ext_y_array(ui_Chart1, ui_Chart1_series_1, ui_Chart1_series_1_array);
    ui_Chart1_series_2 = lv_chart_add_series(ui_Chart1, lv_color_hex(0x42CC5A), LV_CHART_AXIS_PRIMARY_Y);
    lv_chart_set_ext_y_array(ui_Chart1, ui_Chart1_series_2, ui_Chart1_series_2_array);
    ui_Chart1_series_3 = lv_chart_add_series(ui_Chart1, lv_color_hex(0xF59E0B), LV_CHART_AXIS_PRIMARY_Y);
    lv_chart_set_ext_y_array(ui_Chart1, ui_Chart1_series_3, ui_Chart1_series_3_array);
    ui_Chart1_series_4 = lv_chart_add_series(ui_Chart1, lv_color_hex(0xE040FB), LV_CHART_AXIS_SECONDARY_Y);
    lv_chart_set_ext_y_array(ui_Chart1, ui_Chart1_series_4, ui_Chart1_series_4_array);

    lv_obj_set_style_text_color(ui_Chart1, lv_color_hex(0x040404), LV_PART_TICKS | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Chart1, 255, LV_PART_TICKS | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Chart1, LV_TEXT_ALIGN_AUTO, LV_PART_TICKS | LV_STATE_DEFAULT);
    lv_obj_set_style_text_decor(ui_Chart1, LV_TEXT_DECOR_NONE, LV_PART_TICKS | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Chart1, &lv_font_montserrat_12, LV_PART_TICKS | LV_STATE_DEFAULT);

    ui_TabPage3 = lv_tabview_add_tab(ui_TabView1, "Health");
    lv_obj_clear_flag(ui_TabPage3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Arc1 = lv_arc_create(ui_TabPage3);
    lv_obj_set_width(ui_Arc1, 200);
    lv_obj_set_height(ui_Arc1, 188);
    lv_obj_set_x(ui_Arc1, -69);
    lv_obj_set_y(ui_Arc1, -3);
    lv_obj_set_align(ui_Arc1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Arc1, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SNAPPABLE);      /// Flags
    lv_arc_set_value(ui_Arc1, 50);

    lv_obj_set_style_arc_color(ui_Arc1, lv_color_hex(0x4040FF), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_Arc1, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_Arc1, 20, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_Arc1, lv_color_hex(0x4A54E7), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Arc1, 255, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_zhishiLabel4 = lv_label_create(ui_Arc1);
    lv_obj_set_width(ui_zhishiLabel4, 124);
    lv_obj_set_height(ui_zhishiLabel4, 35);
    lv_obj_set_x(ui_zhishiLabel4, -4);
    lv_obj_set_y(ui_zhishiLabel4, 63);
    lv_obj_set_align(ui_zhishiLabel4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_zhishiLabel4, "Health");
    lv_obj_set_style_text_color(ui_zhishiLabel4, lv_color_hex(0x4140FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_zhishiLabel4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_zhishiLabel4, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_zhishiLabel4, &lv_font_montserrat_26, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_zhishiLabel2 = lv_label_create(ui_Arc1);
    lv_obj_set_width(ui_zhishiLabel2, 124);
    lv_obj_set_height(ui_zhishiLabel2, 35);
    lv_obj_set_x(ui_zhishiLabel2, -7);
    lv_obj_set_y(ui_zhishiLabel2, -18);
    lv_obj_set_align(ui_zhishiLabel2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_zhishiLabel2, "Nice!");
    lv_obj_set_style_text_color(ui_zhishiLabel2, lv_color_hex(0x4776E6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_zhishiLabel2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_zhishiLabel2, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_zhishiLabel2, &lv_font_montserrat_26, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_zhishiLabel3 = lv_label_create(ui_Arc1);
    lv_obj_set_width(ui_zhishiLabel3, 124);
    lv_obj_set_height(ui_zhishiLabel3, 35);
    lv_obj_set_x(ui_zhishiLabel3, -2);
    lv_obj_set_y(ui_zhishiLabel3, 12);
    lv_obj_set_align(ui_zhishiLabel3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_zhishiLabel3, "24.2%");
    lv_obj_set_style_text_color(ui_zhishiLabel3, lv_color_hex(0x4471E1), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_zhishiLabel3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_zhishiLabel3, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_zhishiLabel3, &lv_font_montserrat_26, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Dropdown1 = lv_dropdown_create(ui_TabPage3);
    lv_dropdown_set_options(ui_Dropdown1, "Near Day\nNear Week\nNear Month\nNear Year");
    lv_obj_set_width(ui_Dropdown1, 150);
    lv_obj_set_height(ui_Dropdown1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Dropdown1, 116);
    lv_obj_set_y(ui_Dropdown1, -80);
    lv_obj_set_align(ui_Dropdown1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Dropdown1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags

    ui_Dropdown2 = lv_dropdown_create(ui_TabPage3);
    lv_dropdown_set_options(ui_Dropdown2, "Device\nRMP\nTemperature");
    lv_obj_set_width(ui_Dropdown2, 150);
    lv_obj_set_height(ui_Dropdown2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Dropdown2, 117);
    lv_obj_set_y(ui_Dropdown2, -14);
    lv_obj_set_align(ui_Dropdown2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Dropdown2, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags

    ui_SearchBtn = lv_btn_create(ui_TabPage3);
    lv_obj_set_width(ui_SearchBtn, 148);
    lv_obj_set_height(ui_SearchBtn, 48);
    lv_obj_set_x(ui_SearchBtn, 116);
    lv_obj_set_y(ui_SearchBtn, 52);
    lv_obj_set_align(ui_SearchBtn, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_SearchBtn, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_SearchBtn, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_SearchBtn, lv_color_hex(0x609CB7), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SearchBtn, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label1 = lv_label_create(ui_SearchBtn);
    lv_obj_set_width(ui_Label1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label1, "Search");
    lv_obj_set_style_text_font(ui_Label1, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_toSetBtnc1, ui_event_toSetBtnc1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_AiAnalyzeBtnc, ui_event_AiAnalyzeBtnc, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ContorlBtnc, ui_event_ContorlBtnc, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_toChatBtnc1, ui_event_toChatBtnc1, LV_EVENT_ALL, NULL);
}

void ui_Screen2_screen_destroy(void)
{
    if(ui_Screen2) lv_obj_del(ui_Screen2);

    // NULL screen variables
    ui_Screen2 = NULL;
    ui_home1 = NULL;
    ui_toSetBtnc1 = NULL;
    ui_AiAnalyzeBtnc = NULL;
    ui_ContorlBtnc = NULL;
    ui_wenduLabel = NULL;
    ui_zhuangsuLabel = NULL;
    ui_shebeishuLabel = NULL;
    ui_shiduLabel = NULL;
    ui_zhishiLabel1 = NULL;
    ui_yonghumingLabel = NULL;
    ui_TabView1 = NULL;
    ui_TabPage1 = NULL;
    ui_Chart1 = NULL;
    ui_TabPage2 = NULL;
    ui_Chart2 = NULL;
    ui_Chart2_series_1 = NULL;
    ui_Chart2_series_2 = NULL;
    ui_Chart1_series_1 = NULL;
    ui_Chart1_series_2 = NULL;
    ui_Chart1_series_3 = NULL;
    ui_Chart1_series_4 = NULL;
    ui_TabPage3 = NULL;
    ui_Arc1 = NULL;
    ui_zhishiLabel4 = NULL;
    ui_zhishiLabel2 = NULL;
    ui_zhishiLabel3 = NULL;
    ui_Dropdown1 = NULL;
    ui_Dropdown2 = NULL;
    ui_SearchBtn = NULL;
    ui_Label1 = NULL;

}