// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

lv_obj_t * ui_Screen4 = NULL;
lv_obj_t * ui_Image4 = NULL;
lv_obj_t * ui_Image6 = NULL;
lv_obj_t * ui_BackHome1Btnc = NULL;
lv_obj_t * ui_Switch1 = NULL;
lv_obj_t * ui_Switch2 = NULL;
lv_obj_t * ui_LowerLimitPosition = NULL;
lv_obj_t * ui_HighLimitPosition = NULL;
lv_obj_t * ui_CurrentSpeed = NULL;
lv_obj_t * ui_CurrentAcc = NULL;
lv_obj_t * ui_KeyboardSc4up = NULL;
lv_obj_t * ui_GoLeftBtnc = NULL;
lv_obj_t * ui_GoRightBtnc = NULL;
lv_obj_t * ui_GoOnBtnc = NULL;
lv_obj_t * ui_GoStopBtnc = NULL;
lv_obj_t * ui_Back0Btnc = NULL;
lv_obj_t * ui_toSetBtnc2 = NULL;
lv_obj_t * ui_Label5 = NULL;
lv_obj_t * ui_KeyboardSc4down = NULL;
lv_obj_t * ui_TargetLocation = NULL;
lv_obj_t * ui_RoundtripMode = NULL;
lv_obj_t * ui_ConsoleMode = NULL;
// event funtions
void ui_event_BackHome1Btnc(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Screen2, LV_SCR_LOAD_ANIM_NONE, 500, 0, &ui_Screen2_screen_init);
    }
}

void ui_event_LowerLimitPosition(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_FOCUSED) {
        _ui_flag_modify(ui_KeyboardSc4down, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
    }
    if(event_code == LV_EVENT_DEFOCUSED) {
        _ui_flag_modify(ui_KeyboardSc4down, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
    }
    if(event_code == LV_EVENT_FOCUSED) {
        _ui_keyboard_set_target(ui_KeyboardSc4down,  ui_LowerLimitPosition);
    }
}

void ui_event_HighLimitPosition(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_FOCUSED) {
        _ui_flag_modify(ui_KeyboardSc4down, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
    }
    if(event_code == LV_EVENT_DEFOCUSED) {
        _ui_flag_modify(ui_KeyboardSc4down, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
    }
    if(event_code == LV_EVENT_FOCUSED) {
        _ui_keyboard_set_target(ui_KeyboardSc4down,  ui_HighLimitPosition);
    }
}

void ui_event_CurrentSpeed(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_FOCUSED) {
        _ui_flag_modify(ui_KeyboardSc4up, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
    }
    if(event_code == LV_EVENT_DEFOCUSED) {
        _ui_flag_modify(ui_KeyboardSc4up, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
    }
    if(event_code == LV_EVENT_FOCUSED) {
        _ui_keyboard_set_target(ui_KeyboardSc4up,  ui_CurrentSpeed);
    }
}

void ui_event_CurrentAcc(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_FOCUSED) {
        _ui_flag_modify(ui_KeyboardSc4up, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
    }
    if(event_code == LV_EVENT_DEFOCUSED) {
        _ui_flag_modify(ui_KeyboardSc4up, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
    }
    if(event_code == LV_EVENT_FOCUSED) {
        _ui_keyboard_set_target(ui_KeyboardSc4up,  ui_CurrentAcc);
    }
}

void ui_event_GoLeftBtnc(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Screen2, LV_SCR_LOAD_ANIM_NONE, 500, 0, &ui_Screen2_screen_init);
    }
}

void ui_event_GoRightBtnc(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Screen2, LV_SCR_LOAD_ANIM_NONE, 500, 0, &ui_Screen2_screen_init);
    }
}

void ui_event_GoOnBtnc(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Screen2, LV_SCR_LOAD_ANIM_NONE, 500, 0, &ui_Screen2_screen_init);
    }
}

void ui_event_GoStopBtnc(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Screen2, LV_SCR_LOAD_ANIM_NONE, 500, 0, &ui_Screen2_screen_init);
    }
}

void ui_event_Back0Btnc(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Screen2, LV_SCR_LOAD_ANIM_NONE, 500, 0, &ui_Screen2_screen_init);
    }
}

void ui_event_toSetBtnc2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Screen5, LV_SCR_LOAD_ANIM_NONE, 500, 0, &ui_Screen5_screen_init);
    }
}

void ui_event_TargetLocation(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_FOCUSED) {
        _ui_flag_modify(ui_KeyboardSc4down, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
    }
    if(event_code == LV_EVENT_DEFOCUSED) {
        _ui_flag_modify(ui_KeyboardSc4down, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
    }
    if(event_code == LV_EVENT_FOCUSED) {
        _ui_keyboard_set_target(ui_KeyboardSc4down,  ui_TargetLocation);
    }
}

// build funtions

void ui_Screen4_screen_init(void)
{
    ui_Screen4 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image4 = lv_img_create(ui_Screen4);
    lv_img_set_src(ui_Image4, &ui_img_home3_png);
    lv_obj_set_width(ui_Image4, LV_SIZE_CONTENT);   /// 800
    lv_obj_set_height(ui_Image4, LV_SIZE_CONTENT);    /// 479
    lv_obj_set_align(ui_Image4, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image4, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_Image4, 257);

    ui_Image6 = lv_img_create(ui_Screen4);
    lv_img_set_src(ui_Image6, &ui_img_12w_png);
    lv_obj_set_width(ui_Image6, LV_SIZE_CONTENT);   /// 800
    lv_obj_set_height(ui_Image6, LV_SIZE_CONTENT);    /// 480
    lv_obj_set_align(ui_Image6, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image6, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image6, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_BackHome1Btnc = lv_obj_create(ui_Screen4);
    lv_obj_remove_style_all(ui_BackHome1Btnc);
    lv_obj_set_width(ui_BackHome1Btnc, 61);
    lv_obj_set_height(ui_BackHome1Btnc, 50);
    lv_obj_set_x(ui_BackHome1Btnc, -357);
    lv_obj_set_y(ui_BackHome1Btnc, -196);
    lv_obj_set_align(ui_BackHome1Btnc, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_BackHome1Btnc, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Switch1 = lv_switch_create(ui_Screen4);
    lv_obj_set_width(ui_Switch1, 50);
    lv_obj_set_height(ui_Switch1, 25);
    lv_obj_set_x(ui_Switch1, 271);
    lv_obj_set_y(ui_Switch1, -93);
    lv_obj_set_align(ui_Switch1, LV_ALIGN_CENTER);

    ui_Switch2 = lv_switch_create(ui_Screen4);
    lv_obj_set_width(ui_Switch2, 50);
    lv_obj_set_height(ui_Switch2, 25);
    lv_obj_set_x(ui_Switch2, 281);
    lv_obj_set_y(ui_Switch2, 51);
    lv_obj_set_align(ui_Switch2, LV_ALIGN_CENTER);

    ui_LowerLimitPosition = lv_textarea_create(ui_Screen4);
    lv_obj_set_width(ui_LowerLimitPosition, 128);
    lv_obj_set_height(ui_LowerLimitPosition, 43);
    lv_obj_set_x(ui_LowerLimitPosition, 102);
    lv_obj_set_y(ui_LowerLimitPosition, -42);
    lv_obj_set_align(ui_LowerLimitPosition, LV_ALIGN_CENTER);
    lv_textarea_set_placeholder_text(ui_LowerLimitPosition, "Please Input");
    lv_obj_set_style_text_color(ui_LowerLimitPosition, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LowerLimitPosition, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_LowerLimitPosition, lv_color_hex(0x202C31), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_LowerLimitPosition, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_LowerLimitPosition, lv_color_hex(0x5A5F62), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_LowerLimitPosition, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_HighLimitPosition = lv_textarea_create(ui_Screen4);
    lv_obj_set_width(ui_HighLimitPosition, 127);
    lv_obj_set_height(ui_HighLimitPosition, 43);
    lv_obj_set_x(ui_HighLimitPosition, 101);
    lv_obj_set_y(ui_HighLimitPosition, -91);
    lv_obj_set_align(ui_HighLimitPosition, LV_ALIGN_CENTER);
    lv_textarea_set_placeholder_text(ui_HighLimitPosition, "Please Input");
    lv_obj_set_style_text_color(ui_HighLimitPosition, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_HighLimitPosition, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_HighLimitPosition, lv_color_hex(0x202C31), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_HighLimitPosition, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_HighLimitPosition, lv_color_hex(0x5A5F62), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_HighLimitPosition, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_CurrentSpeed = lv_textarea_create(ui_Screen4);
    lv_obj_set_width(ui_CurrentSpeed, 127);
    lv_obj_set_height(ui_CurrentSpeed, 43);
    lv_obj_set_x(ui_CurrentSpeed, 84);
    lv_obj_set_y(ui_CurrentSpeed, 49);
    lv_obj_set_align(ui_CurrentSpeed, LV_ALIGN_CENTER);
    lv_textarea_set_placeholder_text(ui_CurrentSpeed, "Please Input");
    lv_obj_set_style_text_color(ui_CurrentSpeed, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_CurrentSpeed, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_CurrentSpeed, lv_color_hex(0x202C31), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_CurrentSpeed, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_CurrentSpeed, lv_color_hex(0x5A5F62), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_CurrentSpeed, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_CurrentAcc = lv_textarea_create(ui_Screen4);
    lv_obj_set_width(ui_CurrentAcc, 136);
    lv_obj_set_height(ui_CurrentAcc, 43);
    lv_obj_set_x(ui_CurrentAcc, 104);
    lv_obj_set_y(ui_CurrentAcc, 101);
    lv_obj_set_align(ui_CurrentAcc, LV_ALIGN_CENTER);
    lv_textarea_set_placeholder_text(ui_CurrentAcc, "Please Input");
    lv_obj_set_style_text_color(ui_CurrentAcc, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_CurrentAcc, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_CurrentAcc, lv_color_hex(0x202C31), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_CurrentAcc, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_CurrentAcc, lv_color_hex(0x5A5F62), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_CurrentAcc, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_KeyboardSc4up = lv_keyboard_create(ui_Screen4);
    lv_obj_set_width(ui_KeyboardSc4up, 797);
    lv_obj_set_height(ui_KeyboardSc4up, 240);
    lv_obj_set_x(ui_KeyboardSc4up, 4);
    lv_obj_set_y(ui_KeyboardSc4up, -123);
    lv_obj_set_align(ui_KeyboardSc4up, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_KeyboardSc4up, LV_OBJ_FLAG_HIDDEN);     /// Flags

    ui_GoLeftBtnc = lv_obj_create(ui_Screen4);
    lv_obj_remove_style_all(ui_GoLeftBtnc);
    lv_obj_set_width(ui_GoLeftBtnc, 118);
    lv_obj_set_height(ui_GoLeftBtnc, 50);
    lv_obj_set_x(ui_GoLeftBtnc, -311);
    lv_obj_set_y(ui_GoLeftBtnc, -33);
    lv_obj_set_align(ui_GoLeftBtnc, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_GoLeftBtnc, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_GoRightBtnc = lv_obj_create(ui_Screen4);
    lv_obj_remove_style_all(ui_GoRightBtnc);
    lv_obj_set_width(ui_GoRightBtnc, 118);
    lv_obj_set_height(ui_GoRightBtnc, 50);
    lv_obj_set_x(ui_GoRightBtnc, -154);
    lv_obj_set_y(ui_GoRightBtnc, -33);
    lv_obj_set_align(ui_GoRightBtnc, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_GoRightBtnc, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_GoOnBtnc = lv_obj_create(ui_Screen4);
    lv_obj_remove_style_all(ui_GoOnBtnc);
    lv_obj_set_width(ui_GoOnBtnc, 143);
    lv_obj_set_height(ui_GoOnBtnc, 56);
    lv_obj_set_x(ui_GoOnBtnc, 58);
    lv_obj_set_y(ui_GoOnBtnc, 198);
    lv_obj_set_align(ui_GoOnBtnc, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_GoOnBtnc, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_GoStopBtnc = lv_obj_create(ui_Screen4);
    lv_obj_remove_style_all(ui_GoStopBtnc);
    lv_obj_set_width(ui_GoStopBtnc, 133);
    lv_obj_set_height(ui_GoStopBtnc, 56);
    lv_obj_set_x(ui_GoStopBtnc, 205);
    lv_obj_set_y(ui_GoStopBtnc, 198);
    lv_obj_set_align(ui_GoStopBtnc, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_GoStopBtnc, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Back0Btnc = lv_obj_create(ui_Screen4);
    lv_obj_remove_style_all(ui_Back0Btnc);
    lv_obj_set_width(ui_Back0Btnc, 109);
    lv_obj_set_height(ui_Back0Btnc, 56);
    lv_obj_set_x(ui_Back0Btnc, 337);
    lv_obj_set_y(ui_Back0Btnc, 198);
    lv_obj_set_align(ui_Back0Btnc, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Back0Btnc, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_toSetBtnc2 = lv_obj_create(ui_Screen4);
    lv_obj_remove_style_all(ui_toSetBtnc2);
    lv_obj_set_width(ui_toSetBtnc2, 166);
    lv_obj_set_height(ui_toSetBtnc2, 56);
    lv_obj_set_x(ui_toSetBtnc2, -115);
    lv_obj_set_y(ui_toSetBtnc2, -197);
    lv_obj_set_align(ui_toSetBtnc2, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_toSetBtnc2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label5 = lv_label_create(ui_Screen4);
    lv_obj_set_width(ui_Label5, 200);
    lv_obj_set_height(ui_Label5, 33);
    lv_obj_set_x(ui_Label5, 136);
    lv_obj_set_y(ui_Label5, -198);
    lv_obj_set_align(ui_Label5, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label5, "Init OK!");
    lv_obj_set_style_text_color(ui_Label5, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Label5, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label5, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_KeyboardSc4down = lv_keyboard_create(ui_Screen4);
    lv_obj_set_width(ui_KeyboardSc4down, 808);
    lv_obj_set_height(ui_KeyboardSc4down, 254);
    lv_obj_set_x(ui_KeyboardSc4down, 1);
    lv_obj_set_y(ui_KeyboardSc4down, 117);
    lv_obj_set_align(ui_KeyboardSc4down, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_KeyboardSc4down, LV_OBJ_FLAG_HIDDEN);     /// Flags

    ui_TargetLocation = lv_textarea_create(ui_Screen4);
    lv_obj_set_width(ui_TargetLocation, 134);
    lv_obj_set_height(ui_TargetLocation, 43);
    lv_obj_set_x(ui_TargetLocation, 312);
    lv_obj_set_y(ui_TargetLocation, -45);
    lv_obj_set_align(ui_TargetLocation, LV_ALIGN_CENTER);
    lv_textarea_set_placeholder_text(ui_TargetLocation, "Please Input");
    lv_obj_set_style_text_color(ui_TargetLocation, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_TargetLocation, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_TargetLocation, lv_color_hex(0x202C31), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_TargetLocation, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_TargetLocation, lv_color_hex(0x5A5F62), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_TargetLocation, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_RoundtripMode = lv_switch_create(ui_Screen4);
    lv_obj_set_width(ui_RoundtripMode, 50);
    lv_obj_set_height(ui_RoundtripMode, 25);
    lv_obj_set_x(ui_RoundtripMode, 281);
    lv_obj_set_y(ui_RoundtripMode, 97);
    lv_obj_set_align(ui_RoundtripMode, LV_ALIGN_CENTER);

    ui_ConsoleMode = lv_switch_create(ui_Screen4);
    lv_obj_set_width(ui_ConsoleMode, 50);
    lv_obj_set_height(ui_ConsoleMode, 25);
    lv_obj_set_x(ui_ConsoleMode, -260);
    lv_obj_set_y(ui_ConsoleMode, 110);
    lv_obj_set_align(ui_ConsoleMode, LV_ALIGN_CENTER);

    lv_obj_add_event_cb(ui_BackHome1Btnc, ui_event_BackHome1Btnc, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_LowerLimitPosition, ui_event_LowerLimitPosition, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_HighLimitPosition, ui_event_HighLimitPosition, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_CurrentSpeed, ui_event_CurrentSpeed, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_CurrentAcc, ui_event_CurrentAcc, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_GoLeftBtnc, ui_event_GoLeftBtnc, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_GoRightBtnc, ui_event_GoRightBtnc, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_GoOnBtnc, ui_event_GoOnBtnc, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_GoStopBtnc, ui_event_GoStopBtnc, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Back0Btnc, ui_event_Back0Btnc, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_toSetBtnc2, ui_event_toSetBtnc2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_TargetLocation, ui_event_TargetLocation, LV_EVENT_ALL, NULL);

}

void ui_Screen4_screen_destroy(void)
{
    if(ui_Screen4) lv_obj_del(ui_Screen4);

    // NULL screen variables
    ui_Screen4 = NULL;
    ui_Image4 = NULL;
    ui_Image6 = NULL;
    ui_BackHome1Btnc = NULL;
    ui_Switch1 = NULL;
    ui_Switch2 = NULL;
    ui_LowerLimitPosition = NULL;
    ui_HighLimitPosition = NULL;
    ui_CurrentSpeed = NULL;
    ui_CurrentAcc = NULL;
    ui_KeyboardSc4up = NULL;
    ui_GoLeftBtnc = NULL;
    ui_GoRightBtnc = NULL;
    ui_GoOnBtnc = NULL;
    ui_GoStopBtnc = NULL;
    ui_Back0Btnc = NULL;
    ui_toSetBtnc2 = NULL;
    ui_Label5 = NULL;
    ui_KeyboardSc4down = NULL;
    ui_TargetLocation = NULL;
    ui_RoundtripMode = NULL;
    ui_ConsoleMode = NULL;

}
