#!/usr/bin/env python3
"""
RLE 压缩脚本：将 LVGL TRUE_COLOR / TRUE_COLOR_ALPHA 图片
压缩为标签字节 RLE 格式，配合 C 解码器实现按行解压。

用法:
    python compress_rle.py

输出: compressed/ 目录下的新 .c 文件
"""

import os
import re
import sys
from pathlib import Path


INPUT_DIR = Path(r"d:\Code\LVGL_Exp\6-3-bf\main\ui")
OUTPUT_DIR = Path(r"d:\Code\LVGL_Exp\6-3-bf\compressed")


def parse_c_file(filepath: Path) -> dict:
    """解析 C 文件，提取图片元数据和原始像素数据"""
    content = filepath.read_text(encoding="utf-8")

    w_match = re.search(r'\.header\.w\s*=\s*(\d+)', content)
    h_match = re.search(r'\.header\.h\s*=\s*(\d+)', content)
    cf_match = re.search(r'\.header\.cf\s*=\s*(\w+)', content)
    name_match = re.search(r'const lv_img_dsc_t\s+(\w+)\s*=', content)

    if not all([w_match, h_match, cf_match, name_match]):
        raise ValueError(f"无法解析 {filepath}")

    w = int(w_match.group(1))
    h = int(h_match.group(1))
    cf_str = cf_match.group(1)
    name = name_match.group(1)

    # 提取数据数组
    data_match = re.search(
        r'const.*?uint8_t\s+\w+\[\]\s*=\s*\{(.*?)\};',
        content, re.DOTALL
    )
    if not data_match:
        raise ValueError(f"无法提取数据数组: {filepath}")

    data_str = data_match.group(1)
    hex_values = re.findall(r'0x([0-9A-Fa-f]{2})', data_str)
    raw_data = bytes(int(hv, 16) for hv in hex_values)

    # 确定 cf 值和 bytes_per_pixel
    cf_map = {
        "LV_IMG_CF_TRUE_COLOR": (0x04, 2),
        "LV_IMG_CF_TRUE_COLOR_ALPHA": (0x05, 4),
        "LV_IMG_CF_TRUE_COLOR_CHROMA_KEYED": (0x06, 2),
    }
    if cf_str not in cf_map:
        raise ValueError(f"不支持的颜色格式: {cf_str}")

    cf_val, bpp = cf_map[cf_str]

    return {
        "name": name,
        "w": w,
        "h": h,
        "cf_val": cf_val,
        "bpp": bpp,
        "raw_data": raw_data,
    }


def compress_row(raw_bytes: bytes) -> bytes:
    """
    标签字节 RLE 压缩一行数据。
    标签字节:
      bit7=0: 字面量块, bit6-0 = 长度-1 (1~128字节)
      bit7=1: 重复块,   bit6-0 = 重复次数-1 (1~128次), 后跟1字节值
    """
    result = bytearray()
    n = len(raw_bytes)
    i = 0

    while i < n:
        # 统计当前位置开始的连续相同字节数
        run_len = 1
        while i + run_len < n and raw_bytes[i + run_len] == raw_bytes[i] and run_len < 128:
            run_len += 1

        if run_len >= 3:
            # 3个或以上相同字节 → 用重复块编码
            result.append(0x80 | (run_len - 1))
            result.append(raw_bytes[i])
            i += run_len
        else:
            # 不足3个 → 收集字面量块
            lit_start = i
            i += run_len  # 消耗掉这个短重复
            while i < n:
                # 向前看：下一个位置开始是否有 3+ 的重复
                ahead_run = 1
                while i + ahead_run < n and raw_bytes[i + ahead_run] == raw_bytes[i] and ahead_run < 128:
                    ahead_run += 1
                if ahead_run >= 3:
                    break
                i += 1
                if i - lit_start >= 128:
                    break

            lit_len = i - lit_start
            if lit_len > 0:
                result.append(lit_len - 1)  # 0→1字节, 127→128字节
                result.extend(raw_bytes[lit_start:i])

    return bytes(result)


def generate_c_file(info: dict, row_data: list) -> str:
    """
    生成压缩后的 C 文件。
    数据结构:
      [0] original_cf (uint8)
      [1] bytes_per_pixel (uint8)
      [2-3] width (uint16 LE)
      [4-5] height (uint16 LE)
      [6..6+h*4-1] row_offsets[h] (uint32 LE, 绝对偏移)
      [6+h*4..] compressed_rows
    """
    w, h, cf_val, bpp, name = info["w"], info["h"], info["cf_val"], info["bpp"], info["name"]

    # 计算 row_offsets
    header_size = 6 + h * 4  # 头部 + 偏移表
    offsets = []
    current_offset = header_size
    for compressed in row_data:
        offsets.append(current_offset)
        current_offset += len(compressed)

    # 构建完整数据
    data = bytearray()
    data.append(cf_val)
    data.append(bpp)
    data.append(w & 0xFF)
    data.append((w >> 8) & 0xFF)
    data.append(h & 0xFF)
    data.append((h >> 8) & 0xFF)

    for off in offsets:
        data.append(off & 0xFF)
        data.append((off >> 8) & 0xFF)
        data.append((off >> 16) & 0xFF)
        data.append((off >> 24) & 0xFF)

    for compressed in row_data:
        data.extend(compressed)

    # 格式化输出
    lines = []
    lines.append("// Auto-generated by compress_rle.py - RLE compressed")
    lines.append(f"// Original: {name}, {w}x{h}, {bpp} bytes/pixel")
    lines.append(f"// Original size: {info['raw_data_len']} bytes")
    lines.append(f"// Compressed size: {len(data)} bytes")
    lines.append(f"// Compression ratio: {len(data)/info['raw_data_len']*100:.1f}%")
    lines.append("")
    lines.append('#include "ui.h"')
    lines.append("")
    lines.append("#ifndef LV_ATTRIBUTE_MEM_ALIGN")
    lines.append("    #define LV_ATTRIBUTE_MEM_ALIGN")
    lines.append("#endif")
    lines.append("")

    # 数据数组
    lines.append(f"const LV_ATTRIBUTE_MEM_ALIGN uint8_t {name}_data[] = {{")
    for i in range(0, len(data), 16):
        chunk = data[i:i+16]
        hex_str = ", ".join(f"0x{b:02X}" for b in chunk)
        lines.append(f"    {hex_str},")
    lines.append("};")
    lines.append("")

    # 图片描述符
    lines.append(f"const lv_img_dsc_t {name} = {{")
    lines.append(f"    .header.always_zero = 0,")
    lines.append(f"    .header.w = {w},")
    lines.append(f"    .header.h = {h},")
    lines.append(f"    .data_size = sizeof({name}_data),")
    lines.append(f"    .header.cf = LV_IMG_CF_USER_ENCODED_0,")
    lines.append(f"    .data = {name}_data")
    lines.append("};")
    lines.append("")

    return "\n".join(lines)


def main():
    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)

    image_files = sorted(INPUT_DIR.glob("ui_img_*_png.c"))
    if not image_files:
        print(f"未找到图片文件: {INPUT_DIR}")
        sys.exit(1)

    total_original = 0
    total_compressed = 0

    for fpath in image_files:
        print(f"\n处理: {fpath.name}")
        try:
            info = parse_c_file(fpath)
            info["raw_data_len"] = len(info["raw_data"])
            w, h, bpp = info["w"], info["h"], info["bpp"]
            raw = info["raw_data"]

            print(f"  分辨率: {w}x{h}, BPP: {bpp}, 原始: {len(raw)} bytes ({len(raw)/1024:.1f} KB)")

            # 逐行压缩
            row_bytes = w * bpp
            row_data = []
            for y in range(h):
                row = raw[y * row_bytes : (y + 1) * row_bytes]
                compressed = compress_row(row)
                row_data.append(compressed)

            # 计算压缩后总大小
            header_size = 6 + h * 4
            compressed_total = header_size + sum(len(r) for r in row_data)

            # 统计每行压缩率
            row_ratios = [len(r) / row_bytes * 100 for r in row_data]
            avg_ratio = sum(row_ratios) / len(row_ratios)
            min_ratio = min(row_ratios)
            max_ratio = max(row_ratios)

            print(f"  压缩后: {compressed_total} bytes ({compressed_total/1024:.1f} KB)")
            print(f"  压缩率: {compressed_total/len(raw)*100:.1f}% (行均 {avg_ratio:.1f}%, 最佳 {min_ratio:.1f}%, 最差 {max_ratio:.1f}%)")

            # 生成 C 文件
            c_code = generate_c_file(info, row_data)
            out_path = OUTPUT_DIR / fpath.name
            out_path.write_text(c_code, encoding="utf-8")

            total_original += len(raw)
            total_compressed += compressed_total

        except Exception as e:
            print(f"  ❌ 错误: {e}")

    print(f"\n{'='*60}")
    print(f"总计: {total_original/1024:.1f} KB → {total_compressed/1024:.1f} KB")
    print(f"总压缩率: {total_compressed/total_original*100:.1f}%")
    print(f"节省: {(total_original - total_compressed)/1024:.1f} KB")
    print(f"\n输出目录: {OUTPUT_DIR}")
    print(f"请将 compressed/ 下的文件复制到 main/ui/ 替换原文件")
    print(f"同时需要将 lv_img_decoder_rle.c/h 添加到项目，并在 main.c 中调用 lv_img_decoder_rle_init()")


if __name__ == "__main__":
    main()